### ISSUE TITLE
Cordova build fails if I set 'type: modules' in package.json.

### ISSUE THREAD

**Issue by cagross** [apache/cordova-android#1009]
# Bug Report

### What is expected to happen?
`cordova build android` completes without issue.

### What does actually happen?
Build fails with the following output:

    $ cordova build android
    Unable to load PlatformApi from platform. Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: C:\Users\snarl\my-project\platforms\android\cordova\Api.js
    require() of ES modules is not supported.
    require() of C:\Users\snarl\my-project\platforms\android\cordova\Api.js from C:\Users\snarl\AppData\Roaming\npm\node_modules\cordova\node_modules\cordova-lib\src\cordova\util.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
    Instead rename Api.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from C:\Users\snarl\my-project\package.json.
    
    Unhandled error. ('The platform "android" does not appear to be a valid cordova platform. It is missing API.js. android not supported.')

## Information

I've built a simple app, which I can build for Android (or browser) without issue.  I have now now implemented a simple unit test (using [Tape](https://github.com/substack/tape)), which runs in Node.  Since some files I'm testing are ES6 modules, in order to run the unit tests in Node, I had to add `"type": "module",` to my `package.json` file.  But when I did that, my app would no longer build--the Cordova build command fails with the output above.  Is it possible to execute the Cordova build for Android--if so, how?

Or is some part of my method flawed in this case? That is certainly a possibility.  Maybe if I run unit tests in the browser (rather than in Node), this issue will be avoided?

Thanks.

### Command or Code

`cordova build android` (or `cordova build browser`)

### Environment, Platform, Device

Platforms:  Android, Browser

### Version information
Cordova: 9.0.0 (cordova-lib@9.0.1)
Cordova Plugins:  cordova-plugin-file, cordova-plugin-network-information, cordova-plugin-whitelist
Other Frameworks: 
Operating System:  Windows

## Checklist

- [ X ] I searched for existing GitHub issues
- [ X ] I updated all Cordova tooling to most recent version
- [ X ] I included all the necessary information above

**Comment by breautek** [comment]
Cordova doesn't support support ES modules as it is still an experimental technology in node js (which means there are likely to be bugs and drastic changes in the API/behaviour)

In fact the error message seems to indicate this is a bug in NodeJS because `node_modules\cordova-lib\src\cordova\util.js` nearest `package.json` file is `node_modules/cordova-lib/package.json`, and it does not have `"type": "module"` in it, therefore I don't think it's suppose to be treated as an ES file. Nor should it be treated as an ES file because none of cordova sources are not ES modules, they are traditional node modules.

As a workaround I'd probably use another tool that transpiles your code into commonjs so that it can be ran in NodeJS for your unit testing. A popular tool for this kind of thing is Babel, and I believe it has the capability of transpiling ES modules into commonjs.

**Comment by cagross** [comment]
Hey thanks for the reply.  I think the fact that Cordova doesn't support ES modules would explain the behavior I'm experiencing.  But is that stated anywhere in the Cordova documentation?  I looked for it but couldn't see anything about modules.

> as it is still an experimental technology in node js (which means there are likely to be bugs and drastic changes in the API/behaviour)

Didn't Node remove the experimental flag a few releases ago, in Node 13.2.0 ([see here](https://github.com/nodejs/modules/blob/master/doc/archive/plan-for-new-modules-implementation.md))?

> As a workaround I'd probably use another tool that transpiles your code into commonjs so that it can be ran in NodeJS for your unit testing. A popular tool for this kind of thing is Babel, and I believe it has the capability of transpiling ES modules into commonjs.

Yes, thanks for that.  I was going to post back here eventually to say that this is indeed what I did.  I used Browserify (with a Babelify transform) to bundle all the unit testing files in-question into a single JS file.  That allowed me to run that file in Node without issue, and all unit tests were carried out.  This allows me to continue to build my Cordova app.

**Comment by dpogue** [comment]
For some background on what's happening here: When you install Cordova platforms into your project, it creates the native Android project in the `platforms` directory. That native project includes a bunch of Cordova JS libraries to implement the actual build process when you run `cordova prepare` and `cordova build`. However, there's no package.json in that folder, so it inherits the one from the root of your project.

One way to potentially avoid this problem (at the Cordova level) is to reference the platform build scripts via `node_modules` instead of from the `platforms` folder. This is the process that cordova-electron uses, but there are concerns about would impact non-CLI (aka - platform-centered workflow) usage of the Cordova platforms.

**Comment by breautek** [comment]
> Didn't Node remove the experimental flag a few releases ago, in Node 13.2.0 (see here)?

Yes, you don't need the flag to use the feature, but the [API](https://nodejs.org/docs/latest-v14.x/api/esm.html#esm_ecmascript_modules) itself is still in [Stability 1: Experimental](https://nodejs.org/docs/latest-v14.x/api/documentation.html#documentation_stability_index).

> Stability: 1 - Experimental. The feature is not subject to Semantic Versioning rules. Non-backward compatible changes or removal may occur in any future release. Use of the feature is not recommended in production environments.

**Comment by cagross** [comment]
@breautek OK thanks for that explanation.  Did not know about the Stability Index--good to know.
