### ISSUE TITLE
The minSdkVersion is Higher and higher, i couldn't stand it

### ISSUE THREAD

**Issue by JackRo** [apache/cordova-android#1010]
# Feature Request

## Motivation Behind Feature
When i developed my plugin, sometimes i need add the third dependency to my plugin, and the third dependency's minSdkVersion may be more bigger than the Cordova App's minSdkVersion. Then i will get build Error.
And more importantly, i need to let my Cordova App compat the lower minSdkVersion.

## Feature Description
The Cordova App's minSdkVersion could be lower(for example 14) after i npm install cordova-android.
Or i could config my Cordova App's minSdkVersion in the config.xml.

## Alternatives or Workarounds
Now i could add the minSdkVersion gradle config to my Cordova App after npm install cordova-android,
but it is inconvenient.

**Comment by JackRo** [comment]
It is not a Feature Request, i resolve it by config cdvMinSdkVersion in my Cordova App's gradle.properties.

**Comment by breautek** [comment]
While you can override the min sdk to any value, note that  setting this value lower than the cordova default (varies by cordova-android major version) is not recommended or supported. It may or may not work.

**Comment by JackRo** [comment]
@breautek Oh, no, i need override the min sdk to a lower value than cordova-android's minSdkVersion, i hate it may or may not work! ☹️

**Comment by JackRo** [comment]
It just not work well, build error! ☹️

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 19 declared in library [:CordovaLib] /Users/jack/work-flux/FluxTmsApp/platforms/android/CordovaLib/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 14
  	Suggestion: use a compatible library with a minSdk of at most 14,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

**Comment by JackRo** [comment]
@breautek Could you setting the minSdkVersion of cordova-android to lower

**Comment by breautek** [comment]
> @breautek Could you setting the minSdkVersion of cordova-android to lower

No.

> Manifest merger failed : uses-sdk:minSdkVersion 14 cannot be smaller than version 19 declared in library [:CordovaLib] /Users/jack/work-flux/FluxTmsApp/platforms/android/CordovaLib/build/intermediates/library_manifest/debug/AndroidManifest.xml as the library might be using APIs not available in 14
  	Suggestion: use a compatible library with a minSdk of at most 14,
  		or increase this project's minSdk version to at least 19,
  		or use tools:overrideLibrary="org.apache.cordova" to force usage (may lead to runtime failures)

This is the warning by android that you're using two libraries that aren't compatible (because the app min sdk is less than the framework's min sdk). You can suppress this by adding the following in your `config.xml`...

```xml
<edit-config file="AndroidManifest.xml" target="/manifest" mode="merge">
    <manifest xmlns:tools="http://schemas.android.com/tools" />
</edit-config>
<edit-config file="AndroidManifest.xml" target="/manifest/uses-sdk" mode="merge">
    <uses-sdk tools:overrideLibrary="org.apache.cordova" />
</edit-config>
```

I didn't test the above, but it should essentially add the `tools` schema and the `tools:overrideLibrary="org.apache.cordova"` override in the project's `AndroidManifest.xml` file.

Like I said before, this will allow the project to build, but it may crash during runtime on those devices using lower API levels. It's up to you test. This would be an unsupported configuration, so you'll be on your own on issues related to using a lower min sdk.

**Comment by JackRo** [comment]
@breautek Why didn't you consider compatting lower API level. The higher API version will result in compatibility problem!

**Comment by breautek** [comment]
Cordova mainly chooses the min sdk based on market share information.

API levels below 19 do not use chrome as their webview, making it very difficult to support. Increasing the min sdk overtime allows us to simplify the code base when old APIs are obsolete and rarely ever used.

FYI: `cordova-android@9` has min API of 22.
