### ISSUE TITLE
Screen flickering black when html5 video tag comes

### ISSUE THREAD

**Issue by vignesh-balakrishnan** [apache/cordova-android#1031]
# Bug Report

My ionic application starts flickering black screen when video enters into the screen. I’m using html5 video tag in ionic 4.

## Problem

Flickering black screen in application and couldn't use the application any more.

### What is expected to happen?

Video should be played and no flickering should happen

### What does actually happen?

When video starts playing application flickering with black screen and couldn't use the application anymore.

## Information

Here is the video of the issue
video link of the issue : https://lh3.googleusercontent.com/XL-mNnKdyqfjaSX41cRokvJe6_O02b72eEbc6Bz7tWQc4Qz8Qimx94eC8x4sRRz7nWccN56crwsSKA=m37

### Environment, Platform, Device
Android platform, mostly on samsung and one plus devices

### Version information
Ionic:

Ionic CLI : 5.4.6 (C:\Users\TRIO\AppData\Roaming\npm\node_modules\ionic)
Ionic Framework : @ionic/angular 4.11.8
@angular-devkit/build-angular : 0.801.3
@angular-devkit/schematics : 8.1.3
@angular/cli : 8.1.3
@ionic/angular-toolkit : 2.0.0

Cordova:

Cordova CLI : 9.0.0 (cordova-lib@9.0.1)
Cordova Platforms : android 8.1.0
Cordova Plugins : cordova-plugin-ionic-keyboard 2.0.5, cordova-plugin-ionic-webview 4.1.3, (and 22 other plugins)

Utility:

cordova-res : 0.8.1
native-run : 0.2.9 (update available: 0.3.0)

System:

Android SDK Tools : 26.1.1 (C:\Users\TRIO\AppData\Local\Android\Sdk)
NodeJS : v12.11.1 (C:\Program Files\nodejs\node.exe)
npm : 6.11.3
OS : Windows 10

**Comment by SergiusPrado** [comment]
My users have been encountering this as well on my PhoneGap app. A few notes:

* Specifically, it appears to be associated with something in Cordova Android between 6.1.2 to 8.1.0 inclusive, as it immediately started appearing for existing users when they upgraded the app from our Cordova Android 6.1.2 version to an upgraded Cordova 9.0 version (and vignesh is encountering it on Android 8.1.0).
* Haven’t yet isolated it to a specific Chrome or Android version (it appears to exist on Android 9 and 10, at a minimum). I suspect that it is related to the latest Chrome version since I haven’t seen anything about this happening in the past after rather extensive searches.

Cordova:

Cordova CLI : PhoneGap 7.0.0
Cordova Platforms : android 9.0.0
Cordova Plugins :
c.fovea.cordova.purchase
com.hutchind.cordova.plugins.streamingmedia
com.phonegap.plugins.videoplayer
com.rjfun.cordova.plugin.nativeaudio.NativeAudio
cordova-plugin-device
cordova-plugin-dialogs
cordova-plugin-googleplus
cordova-plugin-health
cordova-plugin-inapppurchase
cordova-plugin-splashscreen
cordova-plugin-whitelist
de.appplant.cordova.plugin.local-notification
nl.x-services.plugins.socialsharing
org.apache.cordova.inappbrowser
org.apache.cordova.network-information

System:

Android SDK Tools : 30.0.1
NodeJS : v14.5.0
npm : 6.14.5
OS : MacOS 10.15.4

**Comment by breautek** [comment]
Is this reproducible in a [plain cordova app](https://github.com/apache/cordova-contribute/blob/master/deprecation.md)?

**Comment by vignesh-balakrishnan** [comment]
Yes, I have created a POC for it and its replicating on the same device(samsung m20).
Here is the POC git -- https://github.com/vignesh-balakrishnan/Video-issue.git
Here is the video of it -- https://r6---sn-npoe7n7z.googlevideo.com/videoplayback?expire=1595491955&ei=UyoZX6LDA4f64gL9koPwDw&ip=183.83.155.2&id=999f3b7d15ed7d51&itag=37&source=picasa&begin=0&requiressl=yes&sc=yes&ttl=transient&susc=ph&app=fife&eaua=v79HEybpWU0&mime=video/mp4&cnr=14&dur=25.309&lmt=1595414343017694&sparams=expire,ei,ip,id,itag,source,requiressl,ttl,susc,app,eaua,mime,cnr,dur,lmt&sig=AOq0QJ8wRQIgBRanhDZzK3h22mtvlw2MKK4UfzP2duor0UCz_qx5-oQCIQCH6sQJBvdOF7If8hLo1HPDGQJcx4V3roNpjQ5Xkh762Q==&redirect_counter=1&cm2rm=sn-h55ek7z&req_id=298a99a97856a3ee&cms_redirect=yes&mh=9M&mm=34&mn=sn-npoe7n7z&ms=ltu&mt=1595484739&mv=m&mvi=6&pl=24&lsparams=mh,mm,mn,ms,mv,mvi,pl,sc&lsig=AG3C_xAwRAIgLfeCo37nSl0Q89H4GS6-ZG1djbEtlwCTbTAMX_sDKcwCIC-x1Qw8uju3Jd9oIZal1PHwp3rOH1jyWEVrd9VeG6a-

**Comment by haseebazeem15** [comment]
Any one have solution? I am facing the same issue @vignesh-balakrishnan

**Comment by jcesarmobile** [comment]
this is a chromium bug affecting a few devices, mostly samsung 

https://bugs.chromium.org/p/chromium/issues/detail?id=1109016

**Comment by vignesh-balakrishnan** [comment]
After doing several tests we found that issue arises from the Android system webview's latest update  i.e version 84.0.4147.89.  When i uninstalled it and used it with the default my mobile version 79 there is no issue in the application.
