### ISSUE TITLE
gradle.properties keeps getting overwritten

### ISSUE THREAD

**Issue by sts-ryan-holton** [apache/cordova-android#1058]
# Bug Report

## Problem

When trying to edit `gradle.properties` my settings keep getting overwritten when running `cordova build android`.

### What is expected to happen?

I expect my settings to not be overwritten when I change them.

### What does actually happen?

Settings are getting overwritten.

### Command or Code

I'm setting `android.useAndroidX` to **true** but when I run `cordova build android` it gets set to **false** which isn't the intended behaviour.

### Environment, Platform, Device

Mac
Android

### Version information

Cordova 10
Cordova Android 9.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by Menardi** [comment]
Anything in the `platforms` folder can be overwritten by the build process, so you should avoid editing it.

To enable AndroidX, you should add this line to your `config.xml`:
```
<preference name="AndroidXEnabled" value="true" />
```

**Comment by erisu** [comment]
I am closing out this ticket as resolved. 

As described in the above comment, to enable or disable AndroidX, you need to use the `AndroidXEnabled` preference flag.

This preference flag is configurable in Cordova-Android 9.x.

Since Cordova-Android 10.x release, AndroidX is the only supported library and therefore this flag has been deprecated/removed.
