### ISSUE TITLE
Use apksigner instead of jarsigner

### ISSUE THREAD

**Issue by untilbit** [apache/cordova-android#1077]
### Issue Type

- [ ] Bug Report
- [x] Feature Request
- [ ] Support Question

## Description

I want to sign my apk generated with cordova cli using certificate scheme v1 and v2 just like in Android studio?

Is this supported? How can I pass apksigner options to cordova cli

## Checklist

- [x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by y0nd0** [comment]
Cordova can sign the apk? That would be new to me. I sign my app with `jarsigner`. But also tried the `apksigner`. But note: You also have to use `zipalign`. And depending on what you use it works different. 

If you use jarsigner, you use zipalign AFTER the signing. With apksigner, you have to do this BEFORE signing. [See docs](https://developer.android.com/studio/command-line/apksigner). And in my case there is an issue with the APK and zipalign. You have to execute zipalign twice, if you get the error "validation failed". This may fix it. But anyway, in my case `jarsigner` works great. But since a few days I get an error "failed to extract native libraries". Like in the following issue descriped. #1076

**Comment by breautek** [comment]
> Cordova can sign the apk? 

Yes, if you have a `build.json` file at the cordova project root folder (sibling to the `config.xml` file) with the necessary information, ie: path to your keystore file, keystore aliases & password, etc, then cordova will use that information to sign the apk for you.

See the [docs](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#using-buildjson) for more info.

Also note the documentation currently states you can omit the password so that a password prompt will appear. This doesn't work and will be going away in a future release.

I believe Cordova uses jarsigner internally, but not 100% sure, I'd have to dig through the sources to be sure.

**Comment by y0nd0** [comment]
Ok, great. (including zipalign?) I'll try it. Thanks for the hint. ❤️ Hopefully this will solve my issue with the referred issue above. ...

**Comment by breautek** [comment]
> (including zipalign?) 

Yes.

You can also specify the same, or two different keystores; one for debug builds and another for release builds. I use the same keystore for both variants cause it's annoying having install errors cause the app is already installed signed with a different keystore.

**Comment by infacto** [comment]
Thanks, the build.json made it.

> Important: In the second half of 2021, new apps will be required to publish with the [Android App Bundle](https://developer.android.com/guide/app-bundle) on Google Play. New apps larger than 150 MB must use either [Play Feature Delivery](https://developer.android.com/guide/app-bundle/dynamic-delivery) or [Play Asset Delivery](https://developer.android.com/guide/app-bundle/asset-delivery).

> Note: You can not use apksigner to sign your app bundle. ([bundletool](https://developer.android.com/studio/command-line/bundletool))

This may not be a future-proof feature.

**Comment by breautek** [comment]
> Important: In the second half of 2021, new apps will be required to publish with the Android App Bundle on Google Play.

Good to know. Cordova supports building app bundles as of cordova-android version 8.1, but 9.0 includes some important bug fixes in bundle building.

> This (using apksigner) may not be a future-proof feature. But idk, just an info for you.

You're right. Bundles must use the `jarsigner` according to the [bundletool](https://developer.android.com/studio/command-line/bundletool) docs.

But how we currently sign both apks and bundles is through the android gradle plugin tool so this may be already handled by that plugin. We don't use jarsigner or apksigner directly. I'd imagine google decides the best option to use.

The `signingConfig` has two properties, to enable v1 and v2 signing but we don't specify either. According to this [blog post](https://android-developers.googleblog.com/2016/11/understanding-apk-packaging-in-android-studio-2-2.html), both are enabled by default. So I'm not sure what the behaviour is.

**Comment by erisu** [comment]
I am closing this ticket as the signer tools is being controlled by the Android Gradle Plugin.

We are not specificly choosing which tool is being used.

As for using "certificate scheme v1 and v2", you would need to enable them in the `signingConfigs`:

Example:
```gradle
android {
  signingConfigs {
    release {
      v1SigningEnabled true
      v2SigningEnabled true
    }
  }
}
```

We are not specifically enabling or disabling any of these. We are just using the defaults that AGP determins.

You should be able to enable them by creating a `build-extras.gradle` file and copying it to the appropriate location with a `before_build` hook script.

Please see Cordova docs for more on this:
* https://cordova.apache.org/docs/en/10.x/guide/appdev/hooks/index.html
* https://cordova.apache.org/docs/en/10.x/guide/platforms/android/#extending-buildgradle

**Additional Note:**

* V1 signing uses the JAR signature. This might be how AGP determins to use the `jarsigner`. V2-V4 has APK signatures.
  * https://developer.android.com/reference/tools/gradle-api/7.1/com/android/build/api/variant/SigningConfig
