### ISSUE TITLE
Issues with Cordova and Performanceactive Camera Plugin on Android SDK 29

### ISSUE THREAD

**Issue by ejonnadula** [apache/cordova-android#1105]
# Bug Report
Issues with Cordova and Performanceactive Camera Plugin on Android SDK 29

## Problem
I'm trying to maintain a legacy mobile application that's making use of the performanceactive phonegap custom camera plugin on Cordova 5.1.1 for android. When building the APK for this app using targetSdkVersion 28, everything works fine. But when building using targetSdkVersion 29, the application crashes immediately on startup on Android 10 devices. There's no issue on devices running lower versions of android. Similarly, Android 10 devices work file as long as camera permissions are not provided.

Unfortunately, I don't have access to any further logging or stack traces. The issue hasn't been reproducible in an emulator so far, and I don't personally have access to any Android 10 test devices. The performanceactive library is old enough and far out of maintenance that I wasn't able to find any recent information regarding android SDK support.

My experience with Cordova and any associated plugin libraries is extremely limited, since this is all legacy. Any suggestions for troubleshooting and resolving crash issues with the camera plugins on Android 10? Or are the libraries and plugins here so old as to make version compatibility issues a near certainty and we'd be better off just upgrading to newer Cordova and plugin versions before anything else?

Android OS version: 10

targetSdkVersion: 29

### Environment, Platform, Device

In Android 10 mobile device I am facing this issue

### Version information
Cordova version: 5.1.1
Cordova -Android : 5.1.1
Cordova -ios: 4.1.1
Camera plugin info: performanceactive camera plugin version: 1.4

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
The main breaking change in API 29 I believe is the filesystem changes. Our `cordova-plugin-file` currently has an unpublished fix for this which can be found [here](https://github.com/apache/cordova-plugin-file/pull/417/files).

To prove this is your issue, you'd have to access the android syslog using `adb logcat`. Alternatively you can open the android project in Android Studio, which can be found at `<cordova-root>/platforms/android`, however; because you're using `cordova-android@5.1.1` I don't know if this will work for you. You are probably hitting a security exception.

As far as the third-party plugin goes, learning how to use logcat will probably help you peek at what might be happening.

You're using ancient versions of everything, including versions that are no longer apple compliant. You won't be able to push updates to the iOS app store in it's current state. I would heavily recommend you to spend time to update the Cordova tooling, platforms and plugins and refactor your app to make it work with modern systems. If you need help with this, I'll invite you to our [slack](http://slack.cordova.io/) for support. We try to keep github for tracking bugs only.

**Comment by ejonnadula** [comment]
> The main breaking change in API 29 I believe is the filesystem changes. Our `cordova-plugin-file` currently has an unpublished fix for this which can be found [here](https://github.com/apache/cordova-plugin-file/pull/417/files).
> 
> To prove this is your issue, you'd have to access the android syslog using `adb logcat`. Alternatively you can open the android project in Android Studio, which can be found at `<cordova-root>/platforms/android`, however; because you're using `cordova-android@5.1.1` I don't know if this will work for you. You are probably hitting a security exception.
> 
> As far as the third-party plugin goes, learning how to use logcat will probably help you peek at what might be happening.
> 
> You're using ancient versions of everything, including versions that are no longer apple compliant. You won't be able to push updates to the iOS app store in it's current state. I would heavily recommend you to spend time to update the Cordova tooling, platforms, plugins and refactor your app to make it work with modern systems. If you need help with this, I'll invite you to our [slack](http://slack.cordova.io/) for support. We try to keep github for tracking bugs only.

Thanks Breautek, after uninstalling Performanceactive Camera Plugin my android version of app is not crashing.
We are planning to use "cordova-plugin-camera". For our requirement we have to display overlay border while taking pic in APK and IPA apps. Is there any "cordova-plugin-camera" fork available with customized camera? Or is it possible to add overlay border with "cordova-plugin-camera" plugin?

**Comment by breautek** [comment]
> For our requirement we have to display overlay border while taking pic in APK and IPA apps.

I can't really speak for iOS apps because I have less knowledge of the inner workings on iOS but this isn't possible with our `cordova-plugin-camera`. I'll explain why.

Android has a concept called "Intents". An intent allows us to do trigger an action without necessary having the permissions to do that action. We do this by delegating the action to another app that does have those permissions. The Apache cordova plugin uses intents to use the camera, which means it uses whatever camera app is available on the phone. We have minimal control over the behaviour of the camera itself. In fact your app goes into the background while the camera app is in focus to do it's thing. This allows us to use the camera without explicitly declaring the camera permissions which are considered "dangerous" and google may give you a hard time during app reviews, depending on how you use the camera APIs.

To have full control over the camera view, you'd have to have a plugin that uses the camera APIs directly. And honestly speaking, you'd also have a second challenging, which is displaying a native view alongside a webview in a way that makes sense.

I'll be locking this thread so that we don't get much further off course with the original topic. If you have any other questions, use our [slack](http://slack.cordova.io/), or if you think you've found a bug, then open a new issue.
