### ISSUE TITLE
[HELP] How to intercept requests to local files

### ISSUE THREAD

**Issue by jsbay** [apache/cordova-android#1143]
I am a web developer and I plan to package my web page files into an apk, but there is a js file in my files that will go to the Internet to request a large number of font files. I want to know how I should detect network requests. Forward these requests to the local (local cache of font files).

**Comment by jsbay** [comment]
Or is there a way to expand the cache capacity of the apk? 
Now the font file has set `Response Headers`,like: 
```
HTTP/1.1 200 OK
Server: nginx
Date: Tue, 15 Dec 2020 03:33:06 GMT
Content-Type: application/octet-stream
Last-Modified: Fri, 11 Dec 2020 07:50:37 GMT
Vary: Accept-Encoding
ETag: W/"5fd324cd-df70c"
Expires: Wed, 15 Dec 2021 03:33:06 GMT
Cache-Control: max-age=31536000
Content-Encoding: gzip
```
It will be cached in chrome browser by default
![](http://img.baymax.club/WeChat295688116e4de42652764891d8c84e88.png)
But in the packaged apk, it seems that only a part of it is cached. 
Does the apk limit the size of the cache capacity?
If so, can I modify this limit? How?

**Comment by breautek** [comment]
Is there a reason why you are requesting them over the internet? You really should just package those font files locally and request them locally instead of them.

Your app should work well enough offline. Your app may have parts that require an internet connection, but it should at least be able to load up your base UI code. You will obviously be missing your font files (something a user may see as a buggy app if the font randomly changes) if the user tries using your app without an internet connection.

To answer your question, it isn't easy to "intercept" a request in JS. A normal way of doing this would be via Service Workers, however they don't work in the android webview. You might be able to do this via creating your own [plugin](https://cordova.apache.org/docs/en/latest/guide/hybrid/plugins/) and provide an implementation for:

https://github.com/apache/cordova-android/blob/55feadff0519fa294be34c22ff6fbb913efd1b48/framework/src/org/apache/cordova/CordovaPlugin.java#L292-L319

But the challenge you'll face is "How do you detect if the file is in the chrome cache, and if so how do you obtain it so that you can read and serve it." At this point you're utilising a private implementation detail of the chrome webview, therefore it would be easier and more stable just to bundle your assets with your APK.

Despite my effort of trying to give you a detailed answer, Apache Cordova doesn't provide support in GitHub Issues therefore I'll be closing this ticket. We use GitHub Issues are for tracking bugs or feature requests only. If you require further support, I do invite you to use our [Slack Community](http://slack.cordova.io/) instead.

**Comment by jsbay** [comment]
> Is there a reason why you are requesting them over the internet? You really should just package those font files locally and request them locally instead of them.

This is the online preview of `onlyoffice` used in my app. `Onlyoffice` needs to load a large number of font packages to work properly. The loading action is issued in the js script of **onlyoffice**, so I think the best way is to intercept these font requests globally and use Local font package instead.
