### ISSUE TITLE
Building an Android 10 (API leve 29) App in Cordova using Visual Studio

### ISSUE THREAD

**Issue by mdan25** [apache/cordova-android#1145]
### Issue Type

Hi everyone, I have developed an Android app in Cordova using Visual Studio 2017. While uploading my app to Google Play, 
I got the error:
 "Your app currently targets API level 28 and must target at least API level 29 to ensure it is built 
on the latest APIs optimized for security and performance. Change your app's target API level to at least 29."

Visual Studio 2017 doesn't allow me to use Android 10 or API level above 28 (I've installed on my PC up to api level 30). 
Visual Studio 2019 doesn't support Cordova. 

How can I solve this problem?

Thanks in advance to everyone.

### Version information

Cordova: Cordova 9 (tried also: cordova 10 and cordova-android 9)
Operating System: Visual Studio 2017

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
By default, cordova-android@9 targets API 29.

This may be overrided by a preference in `config.xml`. Check if you have the `android-targetSdkVersion` declared. If so, remove it, or target 29 or higher.

> Visual Studio 2017 doesn't allow me to use Android 10 or API level above 28

I'm not aware of anything inside VS that would limit you from targeting a higher API level, but Cordova is something Microsoft no longer supports in their projects unfortunately. I've never used VS for cordova but if they offered GUI interfaces for settings, perhaps you may have to do things manually now by modifying the config files yourself rather than through a GUI.

Since this doesn't appear to be a bug with Cordova I'll be closing this ticket. If you need further assistance, you can reach out to our [Slack](http://slack.cordova.io/) community.
