### ISSUE TITLE
Documentation Google Play Services missing ?

### ISSUE THREAD

**Issue by FloodGames** [apache/cordova-android#1159]
Isn't it pretty basic to automatically login to your google account in the android version? I tried my hardest but could not find any relevant documentation on this matter. 

![image](https://user-images.githubusercontent.com/60991890/106486375-de824380-64b1-11eb-812d-7bf85007fce3.png)
source: https://developers.google.com/games/services/android/quickstart#step_3_modify_your_code

I have added to config.xml :
`<preference name="GradlePluginGoogleServicesEnabled" value="true" />`

I uploaded a google-services.json file to 
`\platforms\android\app`

End result should be something like this, right? Unfortunately, it's not spawning
![image](https://user-images.githubusercontent.com/60991890/106487492-ff976400-64b2-11eb-9d0d-212afc9554df.png)

I found out that the **ids.xml** mentioned by google is not even being created. Do I need to 'hook' these files after creation?

**Tested on latest version:** Cordova & android

**Comment by breautek** [comment]
> I found out that the ids.xml mentioned by google is not even being created. Do I need to 'hook' these files after creation?

Android Docs says:

> If you are creating an Android game from scratch, you will need to create this file first.

So yes, you need to create the `ids.xml` file yourself. Have a look at the [Hooks API](https://cordova.apache.org/docs/en/9.x/guide/appdev/hooks/index.html). Alternatively, the [config-file](https://cordova.apache.org/docs/en/9.x/plugin_ref/spec.html#config-file) directive can probably also be used in this case as well.

> Isn't it pretty basic to automatically login to your google account in the android version?

I'd be more inclined to leave this kind of thing up to the community to develop blog posts/guides. Cordova's main objective is to provide a packaging tool to package web apps in a native shell. Documenting third-party features is in my opinion out of scope of Cordova's objective.

To conclude on a final note, we use GitHub for tracking issues only. Because this doesn't appear to be a bug, I'll be closing this issue. If you need further assistance, you can try reaching our community on [Slack](http://slack.cordova.io/) or make a post on [StackOverflow](https://stackoverflow.com/questions/tagged/cordova). If you think you've found a bug, then please do open a new issue.

Kind Regards,
Norman
