### ISSUE TITLE
Support for API Level 30

### ISSUE THREAD

**Issue by adityatyagijtg** [apache/cordova-android#1261]
## Problem:
According to the recent deadlines from [Google](https://developer.android.com/distribute/play-policies),
1. August 2021 - New apps must target at least Android 11 (API level 30)
2. November 2021 - Existing apps must target at least Android 11 (API level 30) for new app updates

Currently, the `cordova-android` supports API level 29 and below. My team has apps that are both:
1. Going to have updates in the coming months
2. New apps that'll be going on Play Store in August

As there is no due date, it is a bit difficult for us to plan around deliverables. 

I can see that the cordova-android team is working diligently on the next milestone 10.0.0 (thanks a ton for that), but we'd really appreciate if we could have a due date so that we can plan our deliverables accordingly.
![image](https://user-images.githubusercontent.com/66355672/124594556-8f37a900-de7d-11eb-9fd3-0833cea764f0.png)

## Questions for the team:
1. What is the due date for `cordova-android` v10.0.0?
2. Will `cordova-android` v10.0.0 will be supported with `cordova` v9.x.x?
3. Do we need to update `cordova` from v9.x.x to v10.x.x to use the updated `cordova-android` with API level 30?

Looking forward to positive response.
Thanks!

**Comment by breautek** [comment]
> What is the due date for cordova-android v10.0.0?

We do have a tiny group of dedicated individuals striving to finish everything we want/require in cordova-android@10 and have a release made before the August deadline however, due to the volunteer nature of Apache projects we cannot really provide any accurate timeline for releases and we cannot guarantee that any deadlines will be met.

> Will cordova-android v10.0.0 will be supported with cordova v9.x.x?

We generally only test against and maintain the latest releases. Right now that is Cordova CLI v10, so `cordova-android@10` will only be tested against CLI v10. CLI v9 _may_ work, but mileage may vary and issues arises from using the older CLI won't be addressed.

> Do we need to update cordova from v9.x.x to v10.x.x to use the updated cordova-android with API level 30?

Personally I can't think of any changes that requires `v10` of the CLI, but like mentioned above, cordova-android@10 is not being tested against `v9`

**Comment by breautek** [comment]
I'll be closing this issue since API 30 is already known and we have a milestone set to include everything with the v10 release, but if you have any more questions feel free to ask and I'll try to answer them to the best of my ability.

Alternatively, you can also ask our [Slack](http://slack.cordova.io/) community.

Kind regards,

**Comment by adityatyagijtg** [comment]
@breautek 
Thank you so much for the prompt response. Means a lot!
All the very best to the entire team!
