### ISSUE TITLE
Cordova-android 10 does not find dependencies

### ISSUE THREAD

**Issue by QuentinFarizon** [apache/cordova-android#1320]
# Bug Report

### What is expected to happen?

I migrated from cordova-android 9.1.0 to cordova-android 10.0.1
I'm expecting my project to still build.
I am using Bitrise to get reproducible builds.

### What does actually happen?

I'm getting some errors when building. It seems to not find dependencies that are installed in root node_modules (not in platforms/android/cordova/node_modules). 

```
> cordova build android --release --device --buildConfig /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__001932231/build.json -- --packageType=bundle
Copied android native resourcesUnable to load Platform API from /Users/vagrant/git/platforms/android/cordova/Api.js:
Cannot find module 'nopt'
Require stack:
- /Users/vagrant/git/platforms/android/cordova/lib/prepare.js
- /Users/vagrant/git/platforms/android/cordova/Api.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/index.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/src/help.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/src/cli.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/bin/cordova
```

When I saw that error, I manually added 'nopt' as a dependency to my project's package.json, it "worked", but then it went to the next missing dependency ('osenv') :

```
> cordova build android --release --device --buildConfig /var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/__bitrise-cordova-build-config__960972871/build.json -- --packageType=bundle
Copied android native resourcesUnable to load Platform API from /Users/vagrant/git/platforms/android/cordova/Api.js:
Cannot find module 'osenv'
Require stack:
- /Users/vagrant/git/platforms/android/cordova/node_modules/nopt/lib/nopt.js
- /Users/vagrant/git/platforms/android/cordova/lib/prepare.js
- /Users/vagrant/git/platforms/android/cordova/Api.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/cordova/util.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/index.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/platforms/platforms.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/src/plugman/plugman.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/node_modules/cordova-lib/cordova-lib.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/src/help.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/src/cli.js
- /Users/vagrant/.nvm/versions/node/v14.17.5/lib/node_modules/cordova/bin/cordova
```

Manually added 'osenv' as a dependency to my project's package.json fixes the build issue, but this is really a workaround (and hopefully there was only 2 !).

### Environment, Platform, Device

Xcode 12.1.x, on macOS 10.15.6 (Catalina)
nopt

### Version information

cordova version: 10.0.0
ionic version: 5.4.16
cordova-android : 10.0.1

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
It appears that you upgrade the project incorrectly somehow.

Even though you are saying, in the description, that you are using `cordova-android : 10.0.1`, the stack trace is telling me differently.

```
- /Users/vagrant/git/platforms/android/cordova/node_modules/nopt/lib/nopt.js
- /Users/vagrant/git/platforms/android/cordova/lib/prepare.js
- /Users/vagrant/git/platforms/android/cordova/Api.js
```

In the above snippet of your stack trace, the `prepare.js` file does not exist at that location anymore. Since the stack trace shows it calling this file, it means you still have this file somehow and calling an older version of Cordova-Android. Your project is not using Cordova-Android 10.x.

You should clean your project and try again.

1. Delete `platforms` directory
  * In this case, you might be able to delete specifically the `platforms/android` directory, but generally I delete it all.
1. Delete `plugins` directory
  * If you have any custom plugins in this directory, then you probably should delete only the plugins that are not custom.
1. Delete `node_modules` directory
1. Delete `package-lock.json` file
1. `npm install`
1. `cordova prepare`

If you have any custom modifications directly applied in the platforms directory, you will need to re-apply them after the clean install. 

__note__: Applying any changes directly to the platforms directory or committing the directory to any version control system is not recommended.

**Comment by QuentinFarizon** [comment]
Hello,
Indeed I was hit by this bug :
https://github.com/apache/cordova-fetch/issues/92#issuecomment-898506948

So it was indeed forcing cordova-android 9.1.0, yet not completely since it
was not building as well as being plainly on 9.1.0.
