### ISSUE TITLE
Not working in Android 11

### ISSUE THREAD

**Issue by balaji-subramaniyam** [apache/cordova-android#1333]
Hi team, I just used the **cordova-android@10.1.0** version in my app. It just working fine in android 9 and 10, but it doesn't working on **android 11**. 

The problem I just facing while running on android 11 devices, the app gets opening and stops in splashscreen, further it doesn't proceeded. And also i wish to know which **compileSDKversion** my app is using? I wish i can get a positive solution here.

Thanks in advance :)

**Comment by breautek** [comment]
> And also i wish to know which compileSDKversion my app is using? I

By default, cordova-android@10.x uses API 30. This could be overridden however via the `android-targetSdkVersion` preference. Starting in 10.x both target & compile SDK are synced.

With the information provided, there is no way we can provide a clear answer here. Therefore I'll be closing this issue due to the lack of information. If the app stops at the splash screen, it suggests that you may have a javascript error occurring. You can use chrome's remote debugging tools to see the JS console in the mobile webview.

If you require more assistance, you can try asking our [slack](http://slack.cordova.io/) community. If you find more information and determine that there is a bug with Cordova, then please do create a new issue with the issue form filled out.

Kind regards,
Norman

**Comment by balaji-subramaniyam** [comment]
Thanks alot @breautek
