### ISSUE TITLE
Support for Android SDK 31 - specify an explicit value for android:exported 

### ISSUE THREAD

**Issue by ossraju** [apache/cordova-android#1376]
# Bug Report

### What does actually happen?
build failed 

## Information

Case 1:
create new project using `cordova create hello com.example.hello HelloWorld`
* In config .xml changed the supported like 
`<preference name="android-minSdkVersion" value="22" />
 <preference name="android-targetSdkVersion" value="31" />`
  
*Add  cordova platform android with the command 
`cordova platform add android@10.1.1`
 
 since [cordova plugin whitelist](https://github.com/apache/cordova-plugin-whitelist) is not need for cordova android > 10 
 so removed plugin with the command `cordova plugin remove cordova-plugin-whitelist`
 
 now run `cordova build android`
 
 Build Failed with the error specify an explicit value for android:exported 
 ` Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.`
 
 case 2:  
 removed android platform folder (Just to make sure that error causing by defalut plugin whitelist  which comes when you create a porject )
 using `cordova platform remove android`
 next added platform once again `cordova platform add android@10.1.1`
 
  now run `cordova build android`
 
 Build Failed with the error specify an explicit value for android:exported 
 ` Apps targeting Android 12 and higher are required to specify an explicit value for `android:exported` when the corresponding component has an intent filter defined. See https://developer.android.com/guide/topics/manifest/activity-element#exported for details.`
### Work Around
so I when to android/app/src/AndroidManifest.xml  and i added  android:exported="true" in the Activity Tag 
 ` <activity android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode" android:exported="true" android:label="@string/activity_name" android:launchMode="singleTop" android:name="MainActivity" android:theme="@style/Theme.AppCompat.NoActionBar" android:windowSoftInputMode="adjustResize">
`
then i run command `cordova build android`

Build Successful 

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x ] I included all the necessary information above

**Comment by erisu** [comment]
Already been resolved: https://github.com/apache/cordova-android/pull/1372

**Comment by NelsonChad** [comment]
@erisu i didn't understand the solution on the post, can you help me please?

**Comment by breautek** [comment]
> @erisu i didn't understand the solution on the post, can you help me please?

The explicit export value is required by the app and all android libraries. Cordova manages the app side and has been patched for this since version cordova-android 10.1.2.

If you're running a version before 10.1.2, as indicated in the original post, then you'll need to upgrade to version 10.1.2 or later.

If you still receive this issue after updating to >= 10.1.2, it means there is a plugin installed that is importing an android library that hasn't been patched yet (or the plugin is importing an unpatched version of the library). In this situation, you'll need to track down which plugin is importing the android library that isn't explicitly defining the export value in it's AndroidManifest, and update that plugin, or raise an issue with the plugin's maintainers.
