### ISSUE TITLE
report possible bug in AndroidInsecureFileModeEnabled

### ISSUE THREAD

**Issue by johann50** [apache/cordova-android#1390]
# Bug Report
line 162 in
/framework/org.apache/cordova/engine/SystemWebViewEngine.java
should be

 if (preferences.getBoolean("AndroidInsecureFileModeEnabled", true)) {

or else  AndroidInsecureFileModeEnabled in config.xml
will have the opposite effect.

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
`AndroidInsecureFileModeEnabled` must by default be false. So we cannot switch the boolean flag to `true` as this flag is used as the default value. This is in itself not a bug.

>or else AndroidInsecureFileModeEnabled in config.xml
will have the opposite effect.

Can you elaborate on this?

**Comment by jcesarmobile** [comment]
what `preferences.getBoolean("AndroidInsecureFileModeEnabled", false)` does is:

1. If no `AndroidInsecureFileModeEnabled` is present in the config.xml, the value is false, so doesn't apply the insecure settings.
2. If `AndroidInsecureFileModeEnabled` is present in the config.xml with false value, it doesn't apply the insecure settings.
3. If `AndroidInsecureFileModeEnabled` is present in the config.xml with true value, it applies the insecure settings, so it's working as expected.

changing it to true would apply the insecure settings by default and has no effect on 2 and 3, because on 2 and 3 the value is the one from the config.xml
