### ISSUE TITLE
New Apps require Android API 30+ which Cordova does not provide

### ISSUE THREAD

**Issue by phil294** [apache/cordova-android#1394]
# Bug Report

## Problem

[Cordova's latest Android package supports up to Android API Level 29](https://cordova.apache.org/docs/en/10.x/guide/platforms/android/), but [releasing a new app on Google Play Store requires Android API 30+ since August 2021](https://developer.android.com/google/play/requirements/target-sdk).

### What is expected to happen?

Perhaps I am misunderstanding something, but I would assume to be able to publish a Cordova-created app on Google Play. This seems to be entirely impossible??

### What does actually happen?

When uploading the bundle for an internal testing release, the file is rejected with

  Your app currently targets API level 29 and must target at least API level 30

## Information

It seems this can be bypassed by doing e.g.

```xml
<preference name="android-targetSdkVersion" value="30" />
```

but I don't know
- why this works
- if this actually means android api level 30 support
- if this breaks something

and it's probably a hack anyway (?)

### Environment, Platform, Device

standard config.xml

### Version information

Cordova 10.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by phil294** [comment]
#1261 says that v10 should already be supporting level 30 but I assume it does not, as the docs say 29 max.

**Comment by fredriksthlm** [comment]
<html>
<body>


cordova-android Version | Target Android API-Levels | Equivalent Android Version
-- | -- | --
10.X.X | 30 | 11.0.0
9.X.X |  29 | 10.0.0
8.X.X |  28 |  9.0.0

Now we are waiting for Cordova-Android 11 to be released which will target Android API31, ie Android12



</body>
</html>

**Comment by breautek** [comment]
Docs needs to be updated (it's missing cordova-android 10) but cordova-android@10 is the official version that supports API 30 and will target API 30 by default.

`android-targetSdkVersion` preference can be used to override the target API but it may or may not work on all cordova-android versions (e.g. just because you target a specific API level, doesn't mean the underlying platform code actually **supports** that API level)

I suspect you have cordova-android 9 installed, which by default targets API 29. cordova-android 9 itself will work while targeting API 30 using the aforementioned preference but plugin support may vary.

Closing as not-a-bug. If you have anymore questions, don't hesitate to ask.
