### ISSUE TITLE
`findAll` build tools version return empty

### ISSUE THREAD

**Issue by elihaidv** [apache/cordova-android#1402]
# Bug Report

## Problem
Cannot run on android.
On command `cordova run android` error received:
```
FAILURE: Build failed with an exception.

* Where:
Script 'D:\TickTak\platforms\android\CordovaLib\cordova.gradle' line: 71

* What went wrong:
A problem occurred evaluating script.
> No installed build tools found. Install the Android build tools version 30.0.3 or higher.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.1.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 836ms
Command failed with exit code 1: D:\TickTak\platforms\android\gradlew cdvBuildDebug -b D:\TickTak\platforms\android\build.gradle
```
### What is expected to happen?

Application executed normally

### What does actually happen?
Application build failed

## Information
I've checked my `build-tools` folder and I have them.
I think I find the problem.
In file `platforms\android\CordovaLib\cordova.gradle` in line 63 there is a check about the versions.
When I put this line in comment it works.

### Command or Code
Here are the lines:
```gradle
    def highestBuildToolsVersion = buildToolsDirContents
        .collect { new Version(it) }
        // Invalid inputs will be handled as 0.0.0
        .findAll { it.isHigherThan('0.0.0') && it.isLowerThan(maxVersion) } // Put this line in comment to ignore error
        .max()
```
`highestBuildToolsVersion` is receive null.
But if I print the variable `buildToolsDirContents` I get the folders:
```gradle
    println "buildToolsDirContents: ${buildToolsDirContents.toString()}"
    println "highestBuildToolsVersion: ${highestBuildToolsVersion.toString()}"
```
Output:
```
  buildToolsDirContents: [32.0.0, 33.0.0-rc1]
  highestBuildToolsVersion: null
```

I don't understand why `findAll` remove this versions from results.

### Environment, Platform, Device
Android

### Version information
Windows 10
cordova 11.0.0
node v16.14.0
```

------------------------------------------------------------
Gradle 7.4
------------------------------------------------------------

Build time:   2022-02-08 09:58:38 UTC
Revision:     f0d9291c04b90b59445041eaa75b2ee744162586

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          11.0.11 (JetBrains s.r.o 11.0.11+9-b60-7590822)
OS:           Windows 10 10.0 amd64
```

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
The error message is misleading, and has since been corrected in master (but that patch isn't released yet).

The intent is to find the latest patch version within a specific **major** version. Cordova Android 10 is tested and built against build tools 30, so the tools by default looks for versions specifically in `30.x` range and will filter against `>= 31.x`.

The rationale behind this is to prevent Cordova from attempting to use future versions of the build tools, which as major version changes generally suggest, are breaking.

This behaviour can be overwritten using the `android-buildToolsVersion` preference but Cordova is known to be incompatible with build tools version 31.x, and presumably 32.x.

The recommendation is to install build tools version `30.0.3` (the minimum required by cordova android 10)

**Comment by elihaidv** [comment]
Ok! thanks about the quick response!
