### ISSUE TITLE
Android 12 / API 31 Release

### ISSUE THREAD

**Issue by abhiramesspl** [apache/cordova-android#1416]
When will be the expected release date for following android version ?

Android API - 31 / Android 12

**Comment by breautek** [comment]
Due to the volunteer nature of Apache projects we cannot give accurate release timelines. An Apache member must volunteer their time to make the release.

I can say for certain that it will still be some time. A final patch release for 10.x is being done, then we will start preparing our 11.x release which will include support for API 31, and will be looking to add support for API 32 at the same time. You can keep track of the 11.x progress via the [11.x project](https://github.com/apache/cordova-android/projects/3).
