### ISSUE TITLE
Setting preference hostname causes ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by DarrenPBrown** [apache/cordova-android#1426]
### Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description
I have created a new cordova project and have added android 10.1.2, I have amended the config.xml to include <preference name="hostname" value="ABCDEFG"/> in the hope that I could then change the backend to trust this host and avoid any CORS errors.

## Information
When I launch the app I get an error stating...

Web Page not available

The web page at https://abcdefg/index.html could not be loaded because:

net:ERR_NAME_NOT_RESOLVED

### Command or Code
create a new project using: cordova create testapp3
add the android platform using: cordova platform add android@10.1.2
amend the config.xml to include: <preference name="hostname" value="ABCDEFG"/>
build the project using: cordova build android

### Environment, Platform, Device
Samsung Galaxy J6, Android 10

### Version information
Cordova CLI 11.0.0
cordova android 10.1.2

## Checklist

- [ x] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [ x] I included all the necessary information above

**Comment by DarrenPBrown** [comment]
The config.xml entry that I added to the project and included in the issue has been removed when I submitted the issue so here it is again, this time without the less than and greater than symbols:

preference name="hostname" value="ABCDEFG"/

hope that makes sense.

regards,

Darren.

**Comment by breautek** [comment]
Reproduced and confirmed.

The config:
```
<preference name="hostname" value="ABCDEFG" />
```
will produce the `ERR_NAME_NOT_RESOLVED` error.

The config:
```
<preference name="hostname" value="abcdefg" />
```

On the other hand does work as intended.

It seems something lowercases the hostname as this is the full error:

![Screenshot from 2022-04-27 21-15-37](https://user-images.githubusercontent.com/11200662/165651393-6432e09e-161e-4855-ad26-1edb286a8374.png)

As you can see, even when using upper case, it attempts to load the url in lowercase format.

**Comment by breautek** [comment]
I spent some time on this and I'm not sure if this is solvable by Cordova.

This is because Cordova doesn't lowercase the hostname at all. In fact I traced the code all the way to the point where it passes the URL to the webview to load, which gets passed in as proper casing as authored by the config.

![Screenshot from 2022-04-27 22-56-21](https://user-images.githubusercontent.com/11200662/165661125-112d9f48-9d1e-43c7-beea-28acb0ebfa42.png)

I'm not well knowledgable with domain specs, but [RFC 1035](https://datatracker.ietf.org/doc/html/rfc1035) seems to suggest that domains should be compared case insensitive, and case should be preserved whenever possible. So this _may_ be a bug in the underlying android webview.

**Comment by DarrenPBrown** [comment]
Thank you, if it works fine in lower case then that is fine, I will change the config file.

Thank you for your help.

regards,
Darren.

Darren Brown | Technician | Finance and ICT | Commissioning, Communities and Policy | Derbyshire County Council | County Hall, Matlock, Derbyshire DE4 3AG | Direct dial: 01629 538957
Visit us at www.derbyshire.gov.uk<http://www.derbyshire.gov.uk/> | Follow us on Twitter<http://www.twitter.com/derbyshirecc> | Find us on Facebook<http://www.facebook.com/derbyshirecc> |
