### ISSUE TITLE
Android API level 31 support

### ISSUE THREAD

**Issue by AmirBen78** [apache/cordova-android#1437]
### Issue Type

- [ ] Bug Report
- [ ] Feature Request
- [x] Support Question

## Description
Google announced that Starting in November 2022, app updates must target API level 31 or above and adjust for behavioral changes in Android 12.
According to the documentation : cordova-android version 10.X.X supports API level 22 to 30.
Will the version 11.X.X support API level 31 ? If so when is it planned?

## Checklist

- [x] I searched for already existing GitHub issues about this
- [x] I updated all Cordova tooling to their most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> Will the version 11.X.X support API level 31 ? If so when is it planned?

Yes, v11 will include support for both API 31 and API 32. It will target API 32 by default, but can be lowered using the `android-targetSdkVersion` preference. The changes are already merged into master, so you can test with it using the `nightly` tag.

As for the release timeline, I cannot give any concrete answer due to the volunteer nature of Apache projects.

**Comment by breautek** [comment]
> Hello, Is there a cordova release that can target SDK 31/32 or is still pending ? The cordova I installed with npm builds with SDK 30 and gives error when I try to set 31

See https://cordova.apache.org/announcements/2022/07/12/cordova-android-release-11.0.0.html
