### ISSUE TITLE
Supporting themed app icons for Android 13

### ISSUE THREAD

**Issue by shanlin2dltk** [apache/cordova-android#1450]
# Feature Request
In Android 13, one of the features is supporting themed app icons: https://developer.android.com/about/versions/13/features#themed-app-icons
Do we have a roadmap item to support those configuration in config.xml?

**Comment by breautek** [comment]
Due to the volunteer nature of Apache projects, I cannot give any accurate timelines or roadmaps... but generally speaking, new API features are usually added in major releases.

If someone prepares a pull request and if it can be done without introducing breaking changes, then we can look at adding the feature to a minor release for current version 11.

**Comment by liyamahendra** [comment]
@breautek I think I can fork the project and do necessary changes to have support for Themed Icons. 

Quick questions:
1. Sorry, I'm not aware - do we have Contribution Guidelines?
2. How do you suggest I add this feature? Should I first share the changes I plan to do, get yours/someone from the Cordova team's inputs and then implement the changes in my fork or we (Myself & you or somebody from the Cordova team) work collaboratively on this?

Thanks!

**Comment by breautek** [comment]
Hi @liyamahendra 

The contributor guidelines can be found at https://cordova.apache.org/contribute/contribute_guidelines.html

If you have any high level questions, then it may be best to subscribe and create a thread on our [dev mailing list](https://cordova.apache.org/contact/). Otherwise sometimes the best way to collaborate is to build a PR so that we can review at the code level.

**Comment by liyamahendra** [comment]
@breautek thank you for the details. I joined the dev mailing list. The Contribution guidelines says to have the issue being assigned by one of the committer prior to starting the work.

Would it be okay to have this assigned to me? Anything I need to do prior to this happens?

Thanks again.

**Comment by breautek** [comment]
> The Contribution guidelines says to have the issue being assigned by one of the committer prior to starting the work.

That's actually not a practice I've seen used much here in the Cordova community. The community here is pretty tight knit, so probably not necessary to have explicit assignments. I can see it being useful on larger communities to try to avoid several people working on the same thing. But I don't think that's a strict requirement here.

In short, go for it :D

On a side note, if you're interesting getting more involved, you may want to look into joining our [slack](https://join.slack.com/t/cordova/shared_invite/zt-z70vy6tx-7VNulesO0Qz0Od9QV4tc1Q) channel. We used to use it for providing support but we have since moved to GitHub Discussions. However, we still use slack for realtime chat for some discussions. Dev mailing list is more or less for formal community decisions, as per Apache policies.

**Comment by liyamahendra** [comment]
@breautek I created a [PR](https://github.com/apache/cordova-android/pull/1550) to kick start the work. I added a brief description to the approach that I will be using:

<img width="689" alt="image" src="https://user-images.githubusercontent.com/911879/214263344-c4088f62-e679-4181-a064-28ab39908485.png">

Please comment when you can. 

Thanks!
