### ISSUE TITLE
How to disable the showing splash screen in the app startup 

### ISSUE THREAD

**Issue by merbin2012** [apache/cordova-android#1464]
Previously the splash screen won't display automatically. we can enable it if required. But currently, the splash screen is showing without writing any code. How can I disable it perminantly?

**Comment by breautek** [comment]
As the [Android Docs](https://developer.android.com/guide/topics/ui/splash-screen/migrate) says:

> Starting in Android 12, the system always applies the new [Android system default splash screen](https://developer.android.com/about/versions/12/features/splash-screen) on [cold](https://developer.android.com/topic/performance/vitals/launch-time#cold) and [warm starts](https://developer.android.com/topic/performance/vitals/launch-time#warm) for all apps.

The new splashscreen feature cannot be disabled. This is a limitation of the Android itself and Cordova cannot override this behaviour.

Starting with Android 12 will always display a splashscreen and if one isn't configured, it will default to using your app's icon.
Because Cordova also supports older API devices, cordova-android@11 includes a backwards compatibility provided by Google that implements Android 12 splashscreens for older devices, which mimics Android 12, so that behaviour remains consistent (as closely as possible) across android devices.
