### ISSUE TITLE
Splash Screen does not appear on first launch with Android 12 (cordova-android-11)

### ISSUE THREAD

**Issue by dtarnawsky** [apache/cordova-android#1481]
# Bug Report

## Problem
The Splash Screen does not appear on the first launch of a freshly installed app on an Android 12 device (it does appear afterward)

### What is expected to happen?
The Splash Screen should appear on the first launch of a newly installed app.

### What does actually happen?
The splash screen does not appear on the first launch (but appears with subsequent launches).

## Information

This is using the new AndroidWindowSplashScreenAnimatedIcon preference in config.xml of Cordova Android 11.0.0.

Sample Project exhibiting the issue:
[https://github.com/dtarnawsky/cs-cordova-android-11](https://github.com/dtarnawsky/cs-cordova-android-11)

### Command or Code

cordova platform add android@11
cordova run android

### Environment, Platform, Device

Tested and found as a problem with Samsung S10e and Nexus 5 API 31 (Android 12). Not an issue on Android 10 or Android 11.

### Version information

Cordova CLI 11.0.0
Cordova Android 11.0.0
Plugins:
    cordova-plugin-device: 2.1.0
    cordova-plugin-ionic-keyboard: 2.2.0
    cordova-plugin-ionic-webview: 5.0.0
    cordova-plugin-statusbar: 3.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by fabriciovasc** [comment]
I migrated the cordova and had the same problem. Did you get any solution?

**Comment by jcesarmobile** [comment]
Sadly this is an Android 12 bug on the Splash Screen API itself and Google employees are not going to fix it for Android 12. They have fixed it for Android 13.
It affects all mobile frameworks (and pure native apps using no frameworks) and happens if you launch the app from Android Studio or CLI tooling such as Cordova CLI, native-run, adb, etc.
Doesn't happen when users launch the app from the app icon on their launches (as long as they are using the official android launcher, looks like there is also an issue when using 3rd party launchers)

**Comment by dtarnawsky** [comment]
Any reference to where Google are saying they will not fix the issue?

**Comment by jcesarmobile** [comment]
This link is for a different Splash Screen bug, but they say that the fix won't be available for Android 12 because they are only doing security fixes for Android 12 and those issues are not security related.

https://issuetracker.google.com/issues/242118185#comment2

Some other links about Splash Screen issues on Android 12 and some of them mention that fixes for Android 13 or for the support library (which applies to Android <12) so fixes are coming to Android 13 or Android < 12, but not Android 12:

https://issuetracker.google.com/issues/205021357
https://issuetracker.google.com/issues/207386164
https://issuetracker.google.com/issues/216136037
