### ISSUE TITLE
Getting a build error after migrating our Ionic 5 app from Cordova 10 to Cordova 11

### ISSUE THREAD

**Issue by jeanteke** [apache/cordova-android#1483]
# Bug Report

## Problem
I can't build the apk

### What does actually happen?
I have problem with cordova local notifications plugin

### Command or Code
ionic cordova build android

### Environment, Platform, Device
android platform, windows 10

### Version information
For example:
Cordova: 11.0.0 Cordova CLI: 11.0.0, Cordova Platforms: 11.0.0, Cordova Plugins: localnotification
Other Frameworks: Ionic Framework and CLI version 5
Operating System, Android Studio.
-->

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above

![Captura](https://user-images.githubusercontent.com/87687185/188993933-9ef177c9-e42e-4561-b5ff-f3f51aa9714b.PNG)

**Comment by breautek** [comment]
https://github.com/katzer/cordova-plugin-local-notifications/blob/master/src/android/build/localnotification.gradle#L31

`compile` has been deprecated by Gradle for some time now and cordova-android 11 now uses a gradle version where `compile` has been removed. It is usually as simple as using `implementation` instead, but the plugin maintainers needs to update their plugin.

Closing because this isn't a bug in Cordova.
