### ISSUE TITLE
The cordova project listed on the Xiaomi store prompts that there is a privacy policy issue

### ISSUE THREAD

**Issue by jintaosai314** [apache/cordova-android#1486]
When an app developed with cordova is put on the Xiaomi store, it now prompts: Read personal information without permission.

The specific permission is to get info about installed apps. This seems to be a Xiaomi store specific permission, we have tried other stores, and this is not an issue there.

`action=android.permission.MY_READ_INSTALLED_PACKAGES`

It seems to be the same issue as this Unity ticket:
[https://forum.unity.com/threads/unity-call-queryintentactivitiesasuser-on-start-up-violate-privacy-policy.1209490/](https://forum.unity.com/threads/unity-call-queryintentactivitiesasuser-on-start-up-violate-privacy-policy.1209490/)

**Comment by breautek** [comment]
`MY_READ_INSTALLED_PACKAGES` doesn't appear in the codebase, so it's likely coming from a third-party plugin. I don't think this issue is related with the cordova-android codebase.

If I am wrong, then please open a new issue with the issue form filled out. If you can supply a sample reproduction app that causes `MY_READ_INSTALLED_PACKAGES` permission to be included, then we can probably assist in helping tracking down where the permission is coming from.
