### ISSUE TITLE
`cordova run android` fails with Java 11

### ISSUE THREAD

**Issue by netmikey** [apache/cordova-android#1488]
# Bug Report

### What is expected to happen?

When using Java 11, the build should succeed.

### What does actually happen?

The build fails because of a Java11-incompatible tool.

## Information

When running `cordova run android`, the Gradle build succeeds, but then I get:

```
Checking Java JDK and Android SDK versions
ANDROID_HOME=/Users/me/Library/Android/sdk (recommended setting)
ANDROID_SDK_ROOT=/Users/me/Library/Android/sdk (DEPRECATED)
Using Android SDK: /Users/me/Library/Android/sdk
Reading build config file: /Users/me/myproject/build.json
Command failed with exit code 1: apkanalyzer manifest target-sdk /Users/me/myproject/platforms/android/app/build/outputs/apk/debug/app-debug.apk
Exception in thread "main" java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
	at com.android.repository.api.SchemaModule$SchemaModuleVersion.<init>(SchemaModule.java:156)
	at com.android.repository.api.SchemaModule.<init>(SchemaModule.java:75)
	at com.android.sdklib.repository.AndroidSdkHandler.<clinit>(AndroidSdkHandler.java:81)
	at com.android.tools.apk.analyzer.ApkAnalyzerCli.getAaptInvokerFromSdk(ApkAnalyzerCli.java:277)
	at com.android.tools.apk.analyzer.ApkAnalyzerCli.main(ApkAnalyzerCli.java:129)
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlSchema
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
```

That error is typically what happens if you try to run an application targeted at Java 8 on something like Java 11 or newer. So my best guess is that `apkanalyzer` isn't Java 11 compatible(?)

### Command or Code
`cordova run android`

### Environment, Platform, Device
JDK: 11
Cordova: 11.0.0
Platform: android 11.0.0

### Version information

macOS 12.5.1
Android Studio 3.6.1
Cordova 11.0.0
Platform: android 11.0.0

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
> That error is typically what happens if you try to run an application targeted at Java 8 on something like Java 11 or newer. So my best guess is that apkanalyzer isn't Java 11 compatible(?)

The Android SDK includes old binaries (Which are java apps) that only work on Java 8. Java 11 compatible binaries are available in a separately installed command line package, which can installed from the Android SDK Manager. After installing the package, you should see a folder called `cmdline-tools` in your $ANDROID_HOME folder. You'll need to ensure that `$ANDROID_HOME/cmdline-tools/<version>/bin` is in your `PATH` environment variable. You should also remove the older `$ANDROID_HOME/tools` folder, which contains binaries that requires java 8.

For the cmdline-tools version, the folder will be the version you installed, or `latest` if you install the `(latest)` package.

Let me know if this helps and solves your issue or not.

**Comment by netmikey** [comment]
@breautek yes, thanks a lot! Including `$ANDROID_HOME/cmdline-tools/<version>/bin` in my path solved the issue.

For information: The only thing Android-related I had in my PATH was `$ANDROID_HOME/platform-tools`. Specifically, `$ANDROID_HOME/tools` wasn't in it (so just running `apkanalyzer` on my command line didn't find the binary). So there must have been some fallback mechanism that ended up invoking the "old" tool?

**Comment by breautek** [comment]
The old `apkanalyzer` specifically lives in `$ANDROID_HOME/tools/bin`. Android has some binaries inside `/tools/` and inside `/tools/bin` (They are very organised... /s)

Cordova does first do a `which` check (actually powered by NPM module for cross-platform support) so environmental paths takes precedence over everything. I'm not sure if Cordova has any fallback code to look for these binaries, but I wouldn't be surprised if it does and if they are out-dated. I vaguely recall it does some things and it tends to cause problems anyway because a build doesn't necessarily live in a single process, so something that Cordova might smartly find correctly, may start to fail once it starts running Gradle, for example. If Cordova is doing any fallback code, I'm sure it could be improved, and PRs would be welcomed.

In the [current documentation](https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#setting-environment-variables) we recommend having the following environment variables set:

- PATH
- - /cmdline-tools/<version>/bin (version doesn't seem to matter, docs assumes you're installing the "latest" package)
- - /build-tools/<version> (the version depends on the chosen build tools, generally you'll need the cordova default version, as they often contain breaking changes)
- - /emulator
- - platform-tools

`JAVA_HOME` and `ANDROID_HOME` should be present as well. Docs mentions that `ANDROID_SDK_ROOT` should be set, and it has no harm to have this set to the same value as `ANDROID_HOME`, but `ANDROID_SDK_ROOT` is now deprecated by the android tooling. (Google flip flopped on this environment variable)

I'm going to close this issue as it seems using the environment variables as documented solves the issue
