### ISSUE TITLE
hostname is set via preference, webView is still launched over file:// protocol

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-android#1509]
# Bug Report

## Problem
When hostname is set via preference, webView is still launched over file:// protocol

### What is expected to happen?
webView location hostname should take the hostname as set in preference

### What does actually happen?
webView is loaded over file:// instead of the custom hostname. So cookies can't be set for the proper hostname.

## Information
<preference name="hostname" value="io.globules.test" />

### Environment, Platform, Device
cordova 11
cordova-android 11
android 13 / pixel 4

**Comment by globules-io** [comment]
Turns out this is because `AndroidInsecureFileModeEnabled` was set to `true`

**Comment by globules-io** [comment]
Is this expected behavior? I thought `AndroidInsecureFileModeEnabled ` was only about file:// access even if hostname is used, as compatibility measure? Can someone confirm this is the expected behavior ?

**Comment by breautek** [comment]
`AndroidInsecureFileModeEnabled` flag disables the internal WebviewAssetLoader` which powers the http/s scheme. So yes this is intentional.

You can either use file protocol or not. The API doesn't allow both at the same time. Cordova plugin file 7 offers a way to get a special http url for files saved using the file plugin, which may be want you want.
