### ISSUE TITLE
 window.location.reload() doesn't work anymore

### ISSUE THREAD

**Issue by profenpoche** [apache/cordova-android#1519]
# Bug Report

## Problem

window.location.reload() doesn't work since cordova-android-10

### What is expected to happen?

Current page should reload

### What does actually happen?

Android popup "Application Error"
net::ERR_CONNECTION_REFUSED (https://localhost/<page_name>)

## Information

AndroidInsecureFileModeEnabled=true is suggested as a solution but doesn't work on android 12 (js files won't load at startup : Failed to load resource: net::ERR_FILE_NOT_FOUND  cordova.js:1)

### Command or Code

from chrome inspect or putting a button anywhere in html : window.location.reload()

### Environment, Platform, Device
window 10 and ubuntu 20.04
all android tested failed on reload

### Version information
package.json
"@angular/core": "^14.2.5",
"@ionic/core": "^6.3.0",
"cordova-android": "^11.0.0",

tsconfig:
target : "es2020"

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
What is `<page_name>` name? Is it an actual file path?

e.g. `https://localhost/index.html`?

File not found generally indicates exactly what it says.

**Comment by breautek** [comment]
Ok. If that's the case, then this isn't a bug, there must be file to reload.

If you use clean urls via the history API for example to fake URLs in the standard browser you would encounter the same kind of issue. You cannot reload something that doesn't actually exists. In a traditional web application, this problem is worked around by having a web server handle redirecting and serve the main index page of some sort so that the web application can handle the routing, generally speaking.

In the context of Cordova, there is no webserver to handle that logic, only the underlying filesystem. Because URLs aren't actually shown to the user, it's common practice to use the hash-based routing strategy in Cordova environments instead of using the Clean URL strategy.

**Comment by profenpoche** [comment]
ok i understand the error but it was working before, so it is a regression.
