### ISSUE TITLE
splash size reduced in android 11

### ISSUE THREAD

**Issue by bhargavas12** [apache/cordova-android#1526]
Hello,

After accommodating the splash screen changes in android 11, the size of the splash screen looks reduced.
removed cordova-android-splashscreen plugin and added the below line in config.xml

        <preference name="AndroidWindowSplashScreenAnimatedIcon" value="resources/android/splash/universal-screen.png" />
created the png by following the guidelines from this link
https://developer.android.com/guide/topics/ui/splash-screen#splash_screen_dimensions

png file dimensions are 2732 x 2732

Thanks,
Bhargav

**Comment by breautek** [comment]
2732x2732 appears to be extra large....

For example...

> App icon without an icon background: This should be 288×288 dp, and fit within a circle of 192 dp in diameter.

Android docs says the splashscreen icon should be 288x288dp, where the center has a 192dp circle which is the safe are space for your actual icon. If you use outside of that circle, it may end up clipping.

DP baseline is mdpi density. So mdpi is 1x. So all of these units are treated as pixel units assuming the density is mdpi. You can see the density scale [here](https://developer.android.com/training/multiscreen/screendensities).

xxxhdpi, the largest density is x4. So if you wanted to support the largest density in the crisp manner,  288 x 4 = 1152, so your image I think should be 1152x1152 pixels, with 768px diameter circle in the center being the safe area for your icon. In otherwords, at center point 576,576, you have a 384px radius of space that can be used for your icon.

Let me know if this helps...

**However**, honestly I'm using a 2667x2667 PNG image and that **appears** to be okay across different devices, so I'm not even following my own advice here.

**Comment by jcesarmobile** [comment]
closing since there was no response

**Comment by fabienwnklr** [comment]
hi, any solution ? I have the same issue ..

for example : 

![image](https://user-images.githubusercontent.com/49644785/211764569-ab7893db-4062-44c9-864f-ee7a984b6211.png)

**Comment by rolinger** [comment]
@breautek - I wish Android would just stick to something.  I followed your math and my splash screen is so small now - especially on larger format phones.  There's a lot of real estate around the splash screen icon now - on both small & large format phones - a lot of wasted space.

**Comment by breautek** [comment]
For reference, this is the icon I'm using for our splashscreens

![xxxhdpi](https://user-images.githubusercontent.com/11200662/221367415-3a18d474-d782-4a19-9e28-4627a106766d.png)

Based on a simulator it will look something like this.

![Screenshot from 2022-10-07 13-00-08](https://user-images.githubusercontent.com/11200662/221367450-0684a4a8-b6fc-42ab-8e3c-7072fa13cb28.png)

This size/ratio to screen real estate doesn't really change across devices and is fairly close to the [Google Samples](https://developer.android.com/develop/ui/views/launch/splash-screen)

<img width="3620" alt="splash-screen-composition" src="https://user-images.githubusercontent.com/11200662/221367557-61e16078-5659-47d4-878e-27bb0f69dc92.png">

I don't have the original vectors but roughly overlaid their example and resized the images to match roughly the same resolutions...

![roughAndroidSSComparison](https://user-images.githubusercontent.com/11200662/221367926-4809179a-1245-4d06-8db0-09574f4e59d6.png)

The only devices we haven't really tested is with tablets, since we don't build software for tablets.

**Comment by rolinger** [comment]
@breautek - thanks for sharing.
