### ISSUE TITLE
Can't call API's

### ISSUE THREAD

**Issue by zerealone** [apache/cordova-android#1529]
When I build a debug version of my app and tested it on my android phone, the API's I am using didn't connected to it but when I tested the HTML code itself (with the API's) on my pc it worked just fine.
I am using cordova-android 10.1.1 and 30.0.3 as my android build tools sdk version.
How to solve it?

**Comment by breautek** [comment]
We need a lot more info... like what API your trying to use, how your trying to use it, perhaps some sample code.

Please use the issue template instead of deleting it when you create your issue, it's there for a reason. Help us help you.

**Comment by breautek** [comment]
> I'm sorry for not using the template, I didn't understood how to use it.

Its okay. For next time, when you create an issue it will have sections already in the form for things like version info, description of the problem and the expected vs actual results, etc. It's a guideline that makes it easier triaging issues.

Here's a couple of things to try...

If the api is using http, try using https. Android blocks all http/insecure requests by default. If the weather api doesn't offer a https endpoint, then you can enable cleartext, see https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#android-quirks

If it doesn't help, then you should remote debug your app so that you can gain more insights. If you haven't already, you need to enable developer mode, then inside Developer Options, enable USB Debugging. Then while the device is connected to your computer, inside the desktop Chrome, go to chrome://inspect and you should see your apps webview as a debuggable webview. See https://developer.android.com/studio/debug/dev-options#enable for a more detailed guide for enabling developer options / usb debugging.
