### ISSUE TITLE
Use Cookie ID for XHR Requests on Android Cordova

### ISSUE THREAD

**Issue by El-Tommy** [apache/cordova-android#1533]
I recently had to migrate Cordova Android from version 8 to 10. It turns out that there were many changes in the security of the WebViews and with that, my app no ​​longer stores the Cookie ID for authenticating sessions on my backend server. With each XHR request (GET/POST), it always receives a new cookie/session ID, as it did not send any.

Because of the changes in version 10, I adapted my backend to allow the app to connect to it with the `Access-Control-Allow-Origin` header, and set an alias to my app's `<preference name="hostname" value in the property ="com.myapp.mobile.example-name-site" />`or, should I put exactly the domain it connects to in hostname?

Is it possible to keep the first cookie ID received from the backend and send it in other requests? Or should I change my backend to work with another authentication method, eg Token/Bearer?

**Comment by breautek** [comment]
This is a two prong issue, both of which requires access/changes to the server.

Firstly, the `hostname` preference is for your own app. It should not be the same as a server in which you may want to communicate to. Preferably should be kept to the default value of `localhost`. `"com.myapp.mobile.example-name-site"` should be fine as a value, if you want something different than `localhost`. This preference will change the browser's origin value, so once you pick a value, you should stick with it. Changing origin values means that you'll have different buckets for your local storage, which includes cookies, as they are bound to origins.

Because you're migrating from cordova-android@8 to 10... as of cordova-android 10 we introduced something called a `WebViewAssetLoader`, which is what makes use of the `hostname` preference. The WebViewAssetLoader behaves somewhat like a proxy and makes it so your web app appear as if it's coming from an http(s) server, and changes your origin. So if you have an existing app, that means you will lose access to previously stored objects in your web storage containers. The data is still present on the device, but you do not have direct access to them via the web browser APIs. A migration plugin is necessary to use the `WebViewAssetLoader` and to bring over old data from existing installs. Cordova makes no attempt in migrating data for you.

The purpose of the WebViewAssetLoader is to allow you to use browser features in which requires the document to be loaded from a secure context. A secure context means it must be loaded on an https protocol, which the WebViewAssetLoader emulates.

However if you aren't ready for the data migration and you have important information stored in web storage, then you may opt out of this by using enabling `AndroidInsecureFileModeEnabled` preference. This will make cordova-android revert back to the filesystem strategy as used in cordova-android@9 and earlier versions. I would recommend making an action plan to migrate to the scheme approach to futureproof your app however. The `AndroidInsecureFileModeEnabled` is labelled as insecure because the underlying API that Google provides claims it's insecure. Therefore it's realistic to believe that that API option may become unavailable in the future.

The android chrome webview I don't believe enforces CORS on `file://` based documents, but if it does, your `origin` value will be `null` and you'll need to add the appropriate response headers on your server APIs that your Cordova app hits. I've written an entire [blog post](https://breautek.com/articles/enabling-cors.html) on this (more in the context of WKWebview but the general information also applies to Chrome).

I don't use Cookies in my apps, so I'm less familiar, but I know recent versions of chrome changed the cookie policy where it requires a secure context. This however shouldn't been changed by the cordova-android version, but rather the installed webview version on the device. Additionally the default SameSite policy was changed from `None` to `Lax` on Chrome as of version 90ish (i forget which version specifically). [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite) explains the `SameSite` cookie details, and it's not controllable by the client, but rather the server.

I'm not sure how Chrome enforces cookies when it comes to file-based documents like what would have been used in cordova-android@8, but it's possible that you may require the `WebViewAssetLoader` stuff that was introduced in cordova-android@10. I do know on modern webview versions, when using WebViewAssetLoader, the server must set a `SameSite: None; Secure` when it sets cookies to allow the cookie to be set in a third-party context, which Cordova apps will always be considered third-party.

**Comment by breautek** [comment]
> Really, even using AndroidInsecureFileModeEnabled as true or false, the problem is now generated because of the cookie.
>
> In this case I think I will have to change my backend to support another authentication mode.

Yah, this is inline of what I remember from supporting other users. The cookie change is based on the webview version running on the device and applies regardless of the document scheme.

It's generally solved by using appending `SameSite=None; Secure` to your `Set-Cookie` header/rule. `None` requires `Secure`, and `Secure` means the cookie must be in a secure context, thus you can't use it with `AndroidInsecureFileModeEnabled=true`. You'll need to use the WebViewAssetLoader feature with a `https` scheme. This as explained above will change the document origin of your app, thus your app will start using new storage containers for web storage, which includes cookies, local storage, indexed db, etc. If the data is easily reconstructed that might not be a big deal, but if it's important data that can't be easily reconstructed, then there is a burden of migrating that data using a plugin.

Back in the day when I migrated my apps from crosswalk, I had the same problem and we used https://github.com/totalpave/cordova-plugin-crosswalk-data-migration/tree/totalpave/master to migrate the data. The plugin won't be usable as-is as it was migrating from crosswalk webview -> ionic webview. Also the plugin only migrated local storage, so I'm not sure how to migrate other web storage containers. But you can take a look to see if the file paths still appears to be correct. Modern chrome webviews uses [LevelDB](https://github.com/google/leveldb) to store local storage so that can be used to inspect the contents for testing migrations.

Of course, `AndroidInsecureFileModeEnabled=true` can be used to avoid the origin change, but in your situation, it also means that you may have to use an alternate authentication strategy for your Cordova apps. Personally I use HTTP headers & JWT tokens. I store the JWT token using the cordova file plugin so that I have a flat file on disk if the session should survive app restarts. You could use web storage mediums like localStorage, but I opted to move away from that so I don't have to deal with future potential migrations like I explained above. I've also written a blog on [JWT](https://breautek.com/articles/authenticating-users-using-jwt.html) if you want to explore more on this.

Pros with this approach are:
- Don't deal with cookie related issues (which there is a lot of)
- Fine control that is somewhat decoupled of the browser. You can likely mimick the authentication in other platforms, even outside of the browser.
- JWT promotes authentication without necessary hitting the database

Cons:
- You'll have to manage renew tokens manually if you want that kind of feature
- If using HTTP headers, you have to manually add the header to every API request whereas cookies are automatically included. So you'll likely to build some kind of networking API for your application that does this.
- JWT operates on an expiration concept, and if you use utilise a database-free check, then that also means you can't necessary immediately revoke tokens and they must simply expire. Usually you would have a short-lived access token and a long-lived renew token to balance this problem.

**Comment by breautek** [comment]
Closing as stale.
