### ISSUE TITLE
Unable to debug apps using Chrome/Webview 111 in Android

### ISSUE THREAD

**Issue by lmvco** [apache/cordova-android#1577]
# Bug Report

## Problem
I recently updated the webview of my Android to version 111.x and, after that, I am not able to remote debug my Android app anymore.
In fact, I followed this approach - https://www.girish.in/how-remote-debugging-works-in-chrome/ - to debug my Cordova Android app and it worked until the mentioned update. After that, when opening the socket to the `WebSocketDebuggerUrl` (that I got from sessions list), the socket connection failed (with a 403 forbidden response). Furthermore, I found this error message in Android logs:
```03-29 11:19:21.988  3631  3631 E chromium: [ERROR:devtools_http_handler.cc(766)] Rejected an incoming WebSocket connection from the ws://127.0.0.1:9222 origin. Use the command line flag --remote-allow-origins=ws://127.0.0.1:9222 to allow connections from this origin or --remote-allow-origins=* to allow all origins```

This remote allow origin was, in fact, introduced in Chrome 111 - see [here](https://bugs.chromium.org/p/chromium/issues/detail?id=1422444) - but since in Cordova apps we don't launch Chrome explicitly, I am stuck without being able to debug.

### What is expected to happen?
We need to understand how to provide the `remote-allow-origins` parameter to Android webview so we can debug Cordova Android applications

### What does actually happen?
The debug does not start since the socket connection to debug URL fails with a 403 forbidden response.

## Information
1. When debugging webpages in Chrome desktop, we faced a similar issue when upgrading to Chrome 111 but, as expected, adding the `remote-allow-origins` parameter when launching Chrome was enough to overcome the issue

2. We tried to downgrade the Android Webview to version 110 and this issue did not happen anymore. We were able to debug the Cordova apps using exactly the same code and scripts.

### Environment, Platform, Device
Android 13

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
According to the [chromium bug report](https://bugs.chromium.org/p/chromium/issues/detail?id=14224440) you have posted, the folks there claims that this issue does not occur if you use Chrome to debug rather than other software. I'm not certain what difference that makes since I thought both would be remote but I've I was debugging successfully yesterday and my device is running webview 111 currently (Pretty sure it didn't update overnight).

The instructions provided in https://www.girish.in/how-remote-debugging-works-in-chrome/ seems to be a convoluted or perhaps old school way to debug the webview. DevTools are packaged with Chrome. 

To debug via Chrome you'll need to have:
- ADB in your `PATH` (found inside `$ANDROID_HOME/platform-tools`)
- Chrome for Desktop installed
- An USB Data Cable (not to be confused with a charging cable). Some charging cables are actually data cables, but a data cable is guaranteed to have data lanes. Newer devices (Running API 30 or later I believe) also have the option for wireless debugging, but I'm not too familiar with that since my device is running API 29.

I've already written a [blog post](https://breautek.com/articles/debugging-cordova-apps.html) on how to debug apps using Chrome, but I'll summarise below.

On the desktop, you can go to [chrome://inspect](chrome://inspect), which will bring you to an internal page with debug targets. Your device should appear there. If it doesn't, ensure that ADB sees your device using `adb devices -l`. If ADB lists out empty or doesn't list your device at all, you may need to unplug and replug the USB (ADB is very finicky, and pretty garbage software... a colleague of mine is using the wireless debug feature on his device and it seems much more stable). Once `ADB` sees your device, it should also appear in `chrome://inspect` if you have an app running with a debuggable webview. In cordova, all webviews are debuggable when the app is built using the debug build type (the default as long as the `--release` flag is omitted).

From there, there is an `Inspect` button which will open up Chrome DevTools to debug your webview in the cordova application.

Lastly if that isn't an option, I don't think Cordova can correct the issue. Applications do not have direct access to webview commandline flags. Comandlines flags are read from a specific file on disk which is only used on specialized debug devices. You can see the [Chromium Docs](https://chromium.googlesource.com/chromium/src/+/HEAD/android_webview/docs/commandline-flags.md) for enabling or changing command line flags, which is quite an involved process. Might be feasible to do on an emulator, but a physical device requires reflashing your OS, unless if you have a specialised developer device.  The reason why "consumer" android builds cannot be used is because they have security features turned on that prevents you being able to change these configurations.

Let me know if any of this helps.
