### ISSUE TITLE
themes.xml is missing when adding a new android platform

### ISSUE THREAD

**Issue by aaarichter** [apache/cordova-android#1593]
# Bug Report

## Problem

when running `cordova platform add android` the Cordova guide https://cordova.apache.org/docs/en/11.x/guide/cli/index.html and https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#requirements-and-support does not mention that `/platforms/android/app/src/main/res/values/themes.xml` is missing and should be created 
 
In the cordova guide, after the platform requirements the next step is "building the app" https://cordova.apache.org/docs/en/11.x/guide/cli/index.html#build-the-app, but this build command fails with

```bash
cordova build android
ENOENT: no such file or directory, open '/platforms/android/app/src/main/res/values/themes.xml'
```

### What is expected to happen?

I'd expect that `cordova platform add android` will create a boilerplate `themes.xml` or that the hello world / get started guide has a section that covers it, before building the app.

### What does actually happen?

commands that build or emulate fail with

```bash
ENOENT: no such file or directory, open '/platforms/android/app/src/main/res/values/themes.xml'
```

## Information
cordova v11.1.0
cordova-android v11.0.0

### Command or Code
```bash
cordova create hello
cd hello
cordova platform add android
# fullfill all android requirements
cordova build
```

### Environment, Platform, Device
macOS 13.2.1, Android

### Version information

Cordova CLI 11.1.0, Cordova Platforms,
macOS 13.2.1, Android Studio Electric Eel - 2022.1.1 Patch 2

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by erisu** [comment]
I performed the exact same steps that was provided in the ticket and was unable to reproduce the issue. 

```cmd
cordova create cordovaTest
cordova platform add android
cordova build
```

The above installs `cordova-android@^10.1.1` as expected. This is because of the platform pinning in CLI.

Cordova-Android 10.x does not have `themes.xml` and is not used by Cordova in this version of the platform.

The build was successful.

```log
BUILD SUCCESSFUL in 399ms
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app
Downloading https://services.gradle.org/distributions/gradle-7.1.1-all.zip

...

BUILD SUCCESSFUL in 36s
48 actionable tasks: 48 executed
Built the following apk(s):
	/tmp/cordovaTest/platforms/android/app/build/outputs/apk/debug/app-debug.apk
```

I also tested with the following:

```cmd
cordova create cordovaTest
cordova platform add android@latest
cordova build
```

In the above case, it will install the latest version of `cordova-android` which is in the 11.x range.

Cordova-Android 11.x has the `themes.xml` and is used by Cordova.

Again, the build passed successfuly.

```log
BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
Subproject Path: CordovaLib
Subproject Path: app

...

BUILD SUCCESSFUL in 14s
50 actionable tasks: 50 executed
Built the following apk(s):
	/tmp/cordovaTest/platforms/android/app/build/outputs/apk/debug/app-debug.apk
```

It appears your problem is outside of Cordova's scope and is caused by some external factor that is not mentioned in the tickets information.

I have also tested on macOS 13.2.1

**Comment by aaarichter** [comment]
@erisu thanks for your reply ... I redid the same steps and it works now 🤦‍♂️  - not sure what went wrong in the original hello world project. 

thanks again.
closing issue
