### ISSUE TITLE
Can I continue the cordova app development?

### ISSUE THREAD

**Issue by merbin2012** [apache/cordova-android#1598]
After introducing the Flutter & React native, this repository maintenance is very slow, Cordova-ios updates was done before 2 years and cordova-android update was delay. So I am fear to work with Cordova, currently, I have released more than 120 apps in Play Store and more than 70 apps in iOS made by Cordova. Can you please tell me, can I continue my apps development with cordova, or should I jump to other cross-platform app frameworks?

I had tried other frameworks, but they are not easier than Cordova.

Thank you

**Comment by breautek** [comment]
> Can you please tell me, can I continue my apps development with cordova, or should I jump to other cross-platform app frameworks?

That decision is going to be up to you.

> Cordova-ios updates was done before 2 years

Cordova iOS has been pretty stable since it's last release that didn't really warrant any pushes afaik. The most recent thing that came up with iOS 16.4 was the web inspector change which requires a flag to be explicitly set in the application, which the community provided a fix PR quickly [here](https://github.com/apache/cordova-ios/pull/1300) and is currently in vote process to release `6.3.0` feature update (however the lack of votes seems to indicate that people prefer just to wait for our 7.0 major update).

Is there anything else that you're specifically waiting for?

> cordova-android update was delay.

There's always an ongoing effort for annual releases generally around july/august to keep up with the Target SDK requirement bumps that comes into effect at the end of August. So again, which update was delayed or are there anything specifically you're waiting for?

**Comment by jcesarmobile** [comment]
For asking questions you can use the new GitHub discussions section
https://github.com/apache/cordova/discussions

**Comment by merbin2012** [comment]
Hope Cordova will not discontinued like phonegap, I decided to continue my app development in Cordova. 
Thank you so much for your quick reply
