### ISSUE TITLE
API Level 33

### ISSUE THREAD

**Issue by csi-slizhevskyv** [apache/cordova-android#1599]
Hi,

Does anybody know when a new major cordova-android version will be released that supports API Level 33?

Thanks!

**Comment by breautek** [comment]
I can't give a concrete answer because it's subject to volunteer time but historically we tend to release late july/early august.

API 33 is pretty much ready in our development (master) branch in our core platform however, so you can give it a try. Although I think there might be an upcoming debate on whether to include AGP 8 support (and thus require JDK 17) in the next release, or to defer it for an API 34 support release.

So if you have a use-case where AGP 8 is necessary (afaik AGP 8 is only necessary for API 34 which is still in beta), it would be nice to hear your feedback on https://github.com/apache/cordova-android/pull/1596.

**Comment by nbadiganti** [comment]
Any ETA for Android API Level 33 support release?

Google sent an announcement to upgrade to 33 by August 31st 
https://support.google.com/googleplay/android-developer/answer/11926878

**Comment by erisu** [comment]
Already been release. Please read Cordova Blog for announcements.

https://cordova.apache.org/announcements/2023/05/22/cordova-android-12.0.0.html
