### ISSUE TITLE
Sweetalert did not showing in Android Studio Emulator

### ISSUE THREAD

**Issue by nandhawalrost** [apache/cordova-android#1611]
# Bug Report

### What is expected to happen?
Sweetalert showing in Android Studio Emulator

### What does actually happen?
Sweetalert did not showing in Android Studio Emulator, in other emulator it's showing

### Version information

- Sweetalert2@11
- Cordova 11.1.0
- Android Studio Chipmunk | 2021.2.1 Patch 2
Build #AI-212.5712.43.2112.8815526, built on July 10, 2022
Runtime version: 11.0.12+7-b1504.28-7817840 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 12
Registry: external.system.auto.import.disabled=true

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
If it works in some emulators but not the Android Emulator, then that would suggest it's a bug inside the Android Emulator, not Cordova...

But it's most likely not even an emulator, but rather the webview version you're trying to run it on. Emulators ships with the webview at AOSP of their given versions, they are all quite dated.

If you use a Google Play emulator with the Google Play image, then you can log into the Google Play store and update the system webview to get a modern webview. Older android versions are capped to some degree. Modern webview has a min SDK of API 24/Android 7.

To get more insight on what is actually happening, see the Chrome remote inspector ([see how](https://breautek.com/articles/debugging-cordova-apps.html)).

Closing because this does not appear to be a bug within Cordova.
