### ISSUE TITLE
capacitor-cordova-android-plugins in cordova filetransfer

### ISSUE THREAD

**Issue by RenzoPH** [apache/cordova-android#1622]
Hi, I would like to ask for your help. who's anyone are encounter this issue below? I tried to delete the Whitelist in filetransder and also I tried to  replace into Allowlist but still appearing this issue on my logs even I delete the filetransfer

> Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac
The following annotation processors are not incremental: dagger-compiler-2.8.jar (com.google.dagger:dagger-compiler:2.8).
Make sure all annotation processors are incremental to improve your build speed.
/Users/runner/work/1/s/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:48: error: cannot find symbol
import org.apache.cordova.Whitelist;
                         ^
  symbol:   class Whitelist
  location: package org.apache.cordova
/Users/runner/work/1/s/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:691: error: cannot find symbol
                Whitelist whitelist = (Whitelist)gwl.invoke(webView);
                ^
  symbol:   class Whitelist
  location: class FileTransfer
/Users/runner/work/1/s/android/capacitor-cordova-android-plugins/src/main/java/org/apache/cordova/filetransfer/FileTransfer.java:691: error: cannot find symbol
                Whitelist whitelist = (Whitelist)gwl.invoke(webView);
                                       ^
  symbol:   class Whitelist
  location: class FileTransfer
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors

> Task :capacitor-cordova-android-plugins:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

**Comment by breautek** [comment]
The Apache file transfer plugin is still behind and it's current release is not supported with the current android platform.

The development version of the plugin should install but I believe there are still issues to sort out. I however cannot provide any guidance since `capacitor-cordova-android-plugins` is not something maintained by Apache. If it's a plugin that imports several other plugins including apache's file transfer plugin, then it may be more difficult to swap versions.

Closing because this isn't related to cordova-android.
