### ISSUE TITLE
Error running command "cordova run android"

### ISSUE THREAD

**Issue by Conmi-WhiteJoker** [apache/cordova-android#1647]
# Bug Report
`
> Could not resolve all files for configuration 'classpath'.
   > Could not resolve io.github.g00fy2:versioncompare:1.4.1.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve io.github.g00fy2:versioncompare:1.4.1.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/github/g00fy2/versioncompare/1.4.1/versioncompare-1.4.1.pom'.
            > Could not GET 'https://dl.google.com/dl/android/maven2/io/github/g00fy2/versioncompare/1.4.1/versioncompare-1.4.1.pom'.
`
![image](https://github.com/apache/cordova-android/assets/39817817/83697c57-58f0-444d-b1f6-ac75089ffb08)

## Problem
Maven and google repositories are reporting errors that gradle-7.4.2 cannot be installed, and they both show 404.

### What is expected to happen?
Build android apk.

### What does actually happen?
Could not resolve all files for configuration 'classpath'.

### Command or Code

cordova run android

### Environment, Platform, Device

Platform: Android
Device: Google pixel 3

### Version information

12.0.0 (cordova-lib@12.0.1)

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
While those URLS to the `versioncompare` dependency (which is a dependency used by Cordova) returns 404, I'm unable to reproduce this locally.

I also deleted my `~/.gradle` folder to remove any cached artifacts that gradle may be using instead of downloading which still didn't produce the issue.

Perhaps this was an intermittent issue with google's maven artifact server? Does the issue still persist?

**Comment by breautek** [comment]
Closing as stale.

**Comment by KingBes** [comment]
Is there a solution?

**Comment by kirtikadam** [comment]
Getting same issue @KingBes did you fin any solution?

**Comment by vsmolovik** [comment]
https://github.com/G00fY2/version-compare/releases/tag/1.4.0

**Comment by vsmolovik** [comment]
MOVED TO MAVEN-CENTRAL
future releases will only be available on Maven Central
package name had to be changed due to restrictions of the verification process
logic is untouched
updated build scripts, add GitHub Actions CI and SonarCloud integration
Migration Guide:
Change your Gradle or maven dependency
com.g00fy2:versioncompare:1.3.7
->
io.github.g00fy2:versioncompare:1.4.0

Change you imports
import com.g00fy2.versioncompare.Version
->
import io.github.g00fy2.versioncompare.Version

**Comment by itacolomymariano** [comment]
The error is here(image) for me

![Erro_g00fy2](https://github.com/user-attachments/assets/c87bdd46-e8d3-4f64-9ac1-917db0558d05)


How to solve this

**Comment by jdipallo** [comment]
I am still receiving an error. This is building a Meteor JS Android app. 

* What went wrong:
A problem occurred evaluating root project 'DriveTracker Mobile'.
> Could not resolve all artifacts for configuration 'classpath'.
   > Could not resolve io.github.g00fy2:versioncompare:1.4.0.
     Required by:
         unspecified:unspecified:unspecified
      > Could not resolve io.github.g00fy2:versioncompare:1.4.0.
         > Could not get resource 'https://dl.google.com/dl/android/maven2/io/github/g00fy2/versioncompare/1.4.0/versioncompare-1.4.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /etc/ssl/certs/java/cacerts (No such file or directory)
      > Could not resolve io.github.g00fy2:versioncompare:1.4.0.
         > Could not get resource 'https://repo.maven.apache.org/maven2/io/github/g00fy2/versioncompare/1.4.0/versioncompare-1.4.0.pom'.
            > org.apache.http.ssl.SSLInitializationException: /etc/ssl/certs/java/cacerts (No such file or directory)
