### ISSUE TITLE
Google play won't accept my app-bundle for production version

### ISSUE THREAD

**Issue by lordStrider** [apache/cordova-android#1652]
# Bug Report

I have the following problem!
I am able to compile and push the appbundle to my google console but it says the following: App needs to target Android 13 (API level 33) or higher

I'm using cordova@12.0.0
android sdk 33.0.2 

And so it does not let it be sent to production. Can someone help me?

**Comment by breautek** [comment]
Are you using `cordova-android@12` (not to be confused with `cordova@12`)?

cordova-android@12 defaults targeting API 33.

If you're already using cordova-android@12, then I'd check if you have the `android-targetSdkVersion` preference set, which will override the default.

**Comment by lordStrider** [comment]
Thanks for help.
You say preseting in config.xml `<preference name="android-targetSdkVersion" value="33" />` but in console google shows sdk target is 33
![image](https://github.com/apache/cordova-android/assets/9060364/4e7e37f4-f46a-4419-ad91-1b14c6aaa919) 
My console is in Portuguese

**Comment by breautek** [comment]
The console looks correct to me.

Maybe you should post the original error.

Note that Google has started rolling out warnings which will appear in the console until your app has a fully deployed API 33 update. The warning is just that, a warning for those who don't have an API 33 target app in their production track, and enforcement of consequences will come into effect next week (August 31).

**Comment by lordStrider** [comment]
You are correct is the google warning. When I went to the production area, I was able to follow the process and I didn't understand why it didn't let the test open for production using the shortcuts.

**Comment by 75341704** [comment]
@breautek 
I received the same message from google play.

My project is based on 
Installed platforms:
  android 8.1.0

Will it be ok If the config.xml is modified ( as your mentioned here)
https://github.com/apache/cordova-android/issues/1603#issuecomment-1516811237

Or I have to update cordova-android to the latest version?

**Comment by breautek** [comment]
> You are correct is the google warning. When I went to the production area, I was able to follow the process and I didn't understand why it didn't let the test open for production using the shortcuts.

Ok. Each track does have a release cycle, so you'll have to make sure you deploy an API 33 target update to each track. This doesn't appear to be related to any issues with cordova-android so I'll be closing this issue. I'd suggest using Google Play's documentation and/or support channels if something doesn't appear to be working right with their console.

FWIW, I have apps deployed using cordova-android@12 targeting API 33 with no issues in the Google console.

Of course if it turns out that there is an actionable issue on Cordova side, then please let us know and I can re-open this ticket.

> My project is based on
> Installed platforms:
> android 8.1.0
>
> Will it be ok If the config.xml is modified ( as your mentioned here 33 instead )
> https://github.com/apache/cordova-android/issues/1603#issuecomment-1516811237
>
> Or I have to update cordova-android to the latest version?

cordova-android@8 is out of support. It might be possible to target and compile for API 33 by updating preference settings and it may just work... if so great, if not, you'll likely be on your own for support (with all due respect). Most volunteers providing support will likely just ask you to upgrade to cordova-android@12 if something isn't working right.

Do note that the platform itself doesn't generally have breaking changes when upgrading the target API. It's mostly in feature APIs which are implemented by plugins. So any plugin that is affected by the changes introduced in API 33 will likely declare a requirement on cordova-android@12 for proper API 33 support.
