### ISSUE TITLE
Ignoring exec() from precious page load

### ISSUE THREAD

**Issue by rohanawa** [apache/cordova-android#1657]
# Bug Report

## Problem
Updating  from cordova android 8 to 11.0.0

### What is expected to happen?
Buttons should work

### What does actually happen?
Device event fired after 5 seconds error
Android studio getting ignoring exec from previous page load

### Command or Code

Cordova prepare Android

### Environment, Platform, Device

Android studio giraffe

## Checklist

- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by rohanawa** [comment]
Cordova cli 11
Cordova android 11
Files checked:
Config.xml
Plugins removed and Installed again

**Comment by rohanawa** [comment]
Hi , any resolution to this please

**Comment by breautek** [comment]
> ignoring exec from previous page load

In itself is not an error. it just means that there was an exec call that originated from a page load and you've already navigated off that page, so that call is stale.

I would advise looking up the chrome web inspector and remote debug the webview and see if there are any other JS exceptions going on. https://breautek.com/articles/debugging-cordova-apps.html

If this can easily be reproduced in a sample app, it might be worth sharing a test app too.

**Comment by rohanawa** [comment]
Hi , debugged using Chrome inspect , same issue device ready not fired after 5 seconds

The issue changes on moving to cordova android 10.1.0,

**Comment by breautek** [comment]
> device ready not fired after 5 seconds

Usually this is caused by a plugin either taking a long time to load, or failing to load.

If you're upgrading the cordova-android platform, you might have to check if you have plugins installed that are no longer compatible. If you're coming from cordova-android@8 to current release (which is v12...)

Then some notable plugins are (but not limited to):
- cordova-plugin-whitelist (is now integrated inside the core platform)
- cordova-plugin-androidx (used to enable androidx, modern cordova-android platform forcefully enables androidx)
- cordova-plugin-splashscreen (is now integrated inside the core platform)

note that cordova-android@11 and earlier are out of support since they no longer satisfy Google Play requirements.

**Comment by breautek** [comment]
Closing as stale.
