### ISSUE TITLE
 fail on `cordova platform add android`

### ISSUE THREAD

**Issue by shutaozhenzhen** [apache/cordova-android#1660]
# Bug Report

### What does actually happen?
```
cordova platform add android
Using cordova-fetch for cordova-android@^10.1.2
Adding android project...
Creating Cordova project for the Android platform:
        Path: platforms\android
        Package: com.foxdebug.acodefree
        Name: Acode
        Activity: MainActivity
        Android target: android-33
Subproject Path: CordovaLib
Subproject Path: app
Android project created with cordova-android@10.1.2
Installing "admob-plus-cordova" for android
Subproject Path: CordovaLib
Subproject Path: app
Installing "cordova-plugin-consent" for android
Subproject Path: CordovaLib
Subproject Path: app
ENOENT: no such file or directory, open 'C:\Users\user\Documents\workplace\acode编译\Acode\platforms\android\app\src\main\java\org\apache\cordova\file\FileUtils.java'
```

## Information

trying to build [Acode](https://github.com/deadlyjack/Acode) on windows

## Checklist

- [x] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
The problem comes from their `before_prepare` hook: https://github.com/deadlyjack/Acode/blob/main/hooks/update-mimetype.js

It can't modify files platform files on before_prepare because `prepare` is what setups those files... They probably want `after_prepare` instead...

This isn't a bug with cordova-android, so I'm closing this issue.
