### ISSUE TITLE
What technology does Cordova use to enable JavaScript to call Android or iOS native methods？Is that JSBridge

### ISSUE THREAD

**Issue by EmptyPages** [apache/cordova-android#1679]
What technology does Cordova use to enable JavaScript to call Android or iOS native methods？Is that JSBridge

**Comment by jcesarmobile** [comment]
You can ask questions on the discussions section of cordova repository
https://github.com/apache/cordova/discussions

You can also check the cordova-android code in this repository since it’s public and open source.

both Apple and Google provide APIs for doing that, in example android uses JavascriptInterface

https://developer.android.com/reference/android/webkit/JavascriptInterface
