### ISSUE TITLE
Target date for support to API34

### ISSUE THREAD

**Issue by L035568** [apache/cordova-android#1694]
Apache Cordova uses GitHub Issues as a feature request and bug tracker _only_.
For usage and support questions, please check out the resources below. Thanks!

---

You can get answers to your usage and support questions about **Apache Cordova** on:

* Slack Community Chat: https://cordova.slack.com (you can sign-up at http://slack.cordova.io/)
* StackOverflow: https://stackoverflow.com/questions/tagged/cordova using the tag `cordova`

---

If you are using a tool that uses Cordova internally, like e.g. Ionic, check their support channels:

* **Ionic Framework**
  * [Ionic Community Forum](https://forum.ionicframework.com/)
  * [Ionic Worldwide Slack](https://ionicworldwide.herokuapp.com/)
* **PhoneGap**
  * [PhoneGap Developer Community](https://forums.adobe.com/community/phonegap)

**Comment by breautek** [comment]
Due to the volunteer nature of Apache projects, we cannot give any concrete details on release dates or timelines.

You can subscribe to the [cordova blog](https://cordova.apache.org/blog/) via it's [RSS feed](https://cordova.apache.org/feed.xml) and watch for the Cordova Android 13 release announcement.

Historically, the Cordova community gets together in 1-2 months leading into August to get cordova android release finalised.

https://github.com/apache/cordova-android/pull/1678 is open for review for API 34 support. It will potentially require some breaking changes in your environment (e.g. JDK 17 will be required). Testing and feedback would be appreciated. Details is in the PR.
