### ISSUE TITLE
adjustPan not working properly with API 34

### ISSUE THREAD

**Issue by globules-io** [apache/cordova-android#1723]
# Bug Report

## Problem
With API 33 and using adjustPan, when opening the keyboard the webview resizes, no problem
With API 34 and using adjustPan, when opening the keyboard the webview resizes but the height of the keyboard is greater than the removed height of the webview

## Code
`<custom-preference name="android-manifest/application/activity/@android:windowSoftInputMode" value="adjustPan" />`

## Version
Cordova 12.0.0 (cordova-lib@12.0.1)
cordova-android@13.0.0

**Comment by globules-io** [comment]
![01](https://github.com/user-attachments/assets/b49644f1-c9ed-44f4-b988-82272a40e6d0)
![02](https://github.com/user-attachments/assets/fcb593a2-12c2-482f-9630-7408c32a41bd)

**Comment by breautek** [comment]
`adjustPan` is not suppose to do any resizing. It's suppose to pan the view so that the focused input is always visible, potentially obscuring other UI.

`adjustResize` resizes the view, and if your content is responsive it can be scrolled and such... I think this is maybe what you want instead.

See [android docs](https://developer.android.com/guide/topics/manifest/activity-element#wsoft) for more information.

`adjustResize`:

> The activity's main window is always resized to make room for the soft keyboard on screen.

`adjustPan`:

> The activity's main window isn't resized to make room for the soft keyboard. Rather, the contents of the window automatically pan so that the current focus is never obscured by the keyboard, and users can always see what they are typing. This is generally less desirable than resizing, because the user might need to close the soft keyboard to get at and interact with obscured parts of the window.

If `adjustPan` did any resizing on API 33 it was likely due to a bug in API 33 cause it was never suppose to do any resizing.

**Comment by globules-io** [comment]
I was mistaken, it's a mistake coming originating from a keyboard plugin
