### ISSUE TITLE
Cordova revision older than 10 missing on Maven central

### ISSUE THREAD

**Issue by matteocappello94** [apache/cordova-android#1740]
Older Cordova revision were presente on JCenter and/or spring.io. Now JCenter is unavailable and spring.io requires authentication.

It's possibile to have publish old Cordova revision to Maven central repo?

**Comment by breautek** [comment]
Unfortunately not.

I haven't attempted to build any older cordova-android versions but someone recently was asking about it in the community because they had problems building because of missing dependencies that appears to only been available on JCenter. So without JCenter, it might very difficult to build the framework (and import) the framework in the first place.

Additionally, anything older than the current release of Cordova-Android release is not compliant/compatible with the current Target SDK requirements imposed by Google Play Store (Which currently requires API 34). So releasing older releases takes a lot of effort with very little value.

If your project requires older releases for whatever reason, NPMJS will contain a released packaged framework and template files, so you can source the older releases through NPM. You can also source the original (NPM) tarballs from Apache's SVN Dist repo: https://dist.apache.org/repos/dist/release/cordova/platforms/ . Or if you use the Cordova-CLI you can simply do `cordova platform add android@7` (or whatever version you need). But you'll likely have to source dependencies manually.
