### ISSUE TITLE
EventListener for "menubutton" is never fired

### ISSUE THREAD

**Issue by ooo2003003v2** [apache/cordova-android#1749]
Hello there,
I'm using cordova version 12.0.0 and trying to add a privacy/splash screen to my app when pressing the menu button (bottom bar), but nothing is triggered. I've tried both pause and resume, and they work fine and are logged in the console. So, what is the solution for the 'menu button'?
 
### index.js
```

var app = {
    // Application Constructor
    initialize: function () {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    onDeviceReady: function () {
        this.receivedEvent('deviceready');
    },

    onPause: function () {
        console.log('onPause');
        // Handle the pause event
    },

    onResume: function () {
        console.log('onResume');
        // Handle the resume event
    },

    onMenuKeyDown: function () {
        console.log('onMenuKeyDown');
        // Handle the menubutton event
    },

    // Update DOM on a Received Event
    receivedEvent: function (id) {
        document.addEventListener('pause', this.onPause, false);
        document.addEventListener('resume', this.onResume, false);
        document.addEventListener('menubutton', this.onMenuKeyDown, false);
    },
};

app.initialize();
```

### Screenshot for console log
![image](https://github.com/user-attachments/assets/e9fbd1bd-68c1-4b97-9f34-f12cb3d9cbd2)

### Screenshot for menu button(bottom bar) 
![image](https://github.com/user-attachments/assets/7394edf5-1a32-4420-ab99-10eb9d513c3b)

**Comment by breautek** [comment]
I need to be fact checked on this but I think `menubutton` event only works on the older android devices that actually had a "menu" button (instead of the app switcher that we have now on modern android). I forget when exactly Android made the switch, but I want to say they replaced the menu with the app switcher (Also known as Recent Apps button) in Android 4.0 (API 14). Given that Cordova only supports API 24+ I think the `menubutton` event is completely obsolete.

The docs obviously haven't been updated to reflect this. But if it can be confirmed that I'm correct, then the docs should be updated.

>  trying to add a privacy/splash screen to my app

To do this, you wouldn't listen for the `menubutton` anyway. You'd need a plugin (either by finding one, or [building one](https://cordova.apache.org/docs/en/12.x/guide/hybrid/plugins/index.html) yourself) to set the [FLAG_SECURE](https://developer.android.com/security/fraud-prevention/activities) window flag, which will hide your app's UI while in the app switcher view. This is common for apps that display's sensitive data in the UI.

**Comment by ooo2003003v2** [comment]
> I need to be fact checked on this but I think `menubutton` event only works on the older android devices that actually had a "menu" button (instead of the app switcher that we have now on modern android). I forget when exactly Android made the switch, but I want to say they replaced the menu with the app switcher (Also known as Recent Apps button) in Android 4.0 (API 14). Given that Cordova only supports API 24+ I think the `menubutton` event is completely obsolete.
> 
> The docs obviously haven't been updated to reflect this. But if it can be confirmed that I'm correct, then the docs should be updated.
> 
> > trying to add a privacy/splash screen to my app
> 
> To do this, you wouldn't listen for the `menubutton` anyway. You'd need a plugin (either by finding one, or [building one](https://cordova.apache.org/docs/en/12.x/guide/hybrid/plugins/index.html) yourself) to set the [FLAG_SECURE](https://developer.android.com/security/fraud-prevention/activities) window flag, which will hide your app's UI while in the app switcher view. This is common for apps that display's sensitive data in the UI.

Is that means the corrent cordova implementation has no way to add an event listener to handling when the overview/recentApp button expect creating a plug in?

**Comment by breautek** [comment]
> Is that means the corrent cordova implementation has no way to add an event listener to handling when the overview/recentApp button expect creating a plug in?

Cordova plugins is what runs native code / project modifications, and exposes an API to the webview but I don't think there is even a native API to determine when the user clicks on the recent apps button. So I'm not sure if providing an event for that is even feasible.

When recent apps view is open, your application should go into a pause state I think though, which means the `onPause` event should trigger. But it might also only go into a pause state when your app actually goes into the background (e.g. if the user selects a different app)

>  trying to add a privacy/splash screen to my app when pressing the menu button

If this is your goal, then yah a cordova plugin would be necessary. https://www.npmjs.com/package/cordova-plugin-privacyscreen-enhanced seems to claim to do what you want I think.

**Comment by ooo2003003v2** [comment]
Thx for the help.
