### ISSUE TITLE
Cordova : Nothing in index.js is getting called, no console logs

### ISSUE THREAD

**Issue by kernelfreak** [apache/cordova-android#482]
We are working on a Cordova project where we are developing an app for Android. The app is working good, but for certain functionalities to work properly, we need to access index.js file located in parent-folder/www/js/index.js. We added our modifications there, but nothing from index.js is getting called. We have a simple console.log, which also we don't see. What are we missing?

index.js : 
```

var app = {
    // Application Constructor
    initialize: function() {
        document.addEventListener('deviceready', this.onDeviceReady.bind(this), false);
    },

    // deviceready Event Handler
    //
    // Bind any cordova events here. Common events are:
    // 'pause', 'resume', etc.
    onDeviceReady: function() {
        console.log("i am so ready for u boyyyzzz!");
        this.receivedEvent('deviceready');
        window.addEventListener("click", function(event){
            var closestA = event.closest("a");
            //if(closestA && closestA.href && (closestA.getAttribute("download") !== undefined) && (closestA.getAttribute("download") !== null)){
                var fileTransfer = new FileTransfer();
                var uri = encodeURI(closestA.href);
                var fileURL =  "///storage/emulated/0/DCIM/myFile";

                fileTransfer.download(
                      uri, fileURL, function(entry) {
                         console.log("download complete: " + entry.toURL());
                      },

                      function(error) {
                         console.log("download error source " + error.source);
                         console.log("download error target " + error.target);
                         console.log("download error code" + error.code);
                      }

                   );
            //}
        });
    },
```
This is causing us a lot of issues as none of our external functions, especially download seems to be working. What are we doing wrong. Any insight would help, we are stuck on this for 2 days. Thank you.

**Comment by shaunjohansen** [comment]
I hope you have figured this out and moved on by now! But, just in case you are still stuck...

I strongly suspect the binding is incorrect: `this.onDeviceReady.bind(this)`

As it's written, I believe `this` will resolve to `window` because JavaScript is funny sometimes. Unless this code is wrapped in some JS framework that turns it into an object-oriented object somehow... In which case you haven't provided enough information for someone to help you. ;-)

I would replace the line with something simpler:
```javascript
  document.addEventListener('deviceready', app.onDeviceReady, false);
```

Also, ensure the `initialize` function is called. It is OK to add this `document.addEventListener` outside of any constructor:

```javascript
var app = {
  onDeviceReady: function() {
    console.log("i am so ready for u boyyyzzz!");
  },
};

document.addEventListener('deviceready', app.onDeviceReady, false);
```

Happy coding!

**Comment by jcesarmobile** [comment]
Yeah, looks like a bug on the user code. Closing.
