### ISSUE TITLE
not handling javac 10 and 11

### ISSUE THREAD

**Issue by odrzutowiec** [apache/cordova-android#510]
# Issue description
```cordova run android --emulator``` is not working on java installed via brew (both oracle and openjdk versions).

# Reproduction
- On mac os 10.13.6:
- npm module cordova-android 7.0.0 (installed automatically by cordova platform add android)

### oracle
- brew install oracle_java
- cordova run android --emulator
- fix the JAVA_HOME envvar
- getting ```UnhandledPromiseRejectionWarning: CordovaError: Requirements check failed for JDK 1.8 or greater```

### openjdk
- brew tap brew tap AdoptOpenJDK/openjdk
- brew install adoptopenjdk-openjdk11
- fix the JAVA_HOME envvar
- getting ```UnhandledPromiseRejectionWarning: CordovaError: Requirements check failed for JDK 1.8 or greater```
- i know this is not brew cask, it's a third party brew tap, but as we speak the guys at adoptopenjdk are working on pull request to official brew cask for openjdk

# Investigation
As far as I discovered file check_reqs.js is responsible, it has problem recognising java10 and java11 because javac -version outputs to stdout instead of stderr. Also the regex.

**Comment by dpogue** [comment]
As far as I know, the Android tools require Java 8 and are not compatible with newer versions.

**Comment by raphinesse** [comment]
@odrzutowiec The Problem with `check_reqs.js` has already been fixed in https://github.com/apache/cordova-android/pull/446 but the fix has not been released yet.

However, as @dpogue said: The Android tools require Java 8 (exactly). You can make it work with newer versions in *some* scenarios but it's generally not worth the trouble.

You can try to verify this using `cordova@nightly` and `cordova-android@nightly`. You then should get the message `Requirements check failed for JDK 1.8`

**Comment by hack-r** [comment]
Thank you. Are there any plans to update the support for newer versions?

Oracle makes it verrry hard to find a JDK that old, and this will of course lead to issues for those with modern Java in both USER and SYSTEM fields.
