### ISSUE TITLE
cordova platform add android command is not working in windows 10

### ISSUE THREAD

**Issue by saikiran1264** [apache/cordova-android#545]
Hi,
I have followed exactly the belows steps in my windows 10

npm install -g cordova
cd my_project
cordova platform remove android
cordova platform add android@7.1.2

but after providing "cordova platform add android@7.1.2" command , it is not showing any error or any platform addition.
 output : cordova platform add android@7.1.2
Using cordova-fetch for cordova-android@7.1.2
After this, screen(command prompts) hangs there without showing any progress

whereas in MAC O.S its working fine with above steps. Could you please check and resolve

>cordova --version
8.1.2 (cordova-lib@8.1.1)
>node --version
v10.13.0
>npm --version
6.4.1

**Comment by breautek** [comment]
Apologies for the lack of a response. I'll be closing this issue since it's likely out-dated now.

If you still experience this kind of issue, I would recommend ensuring everything is up to date. You can also add the `--verbose` flag to see more information. My guess is it's waiting on NPM. Example given below:

`cordova platform add android@7.1.2 --verbose`
