### ISSUE TITLE
window.openDatabase Error.. 

### ISSUE THREAD

**Issue by krm0219** [apache/cordova-android#622]
I am creating and using DB at Cordova javascript.
This issue occurs with Android 9.0

The first time you run window.openDatabase, there is no problem.
If you insert a value and restart the app, the problem occurs.

[INFO:CONSOLE(591)] "unable to open database, failed to start transaction (14 enable to open database file)"
[INFO:CONNSOLE(591)] "Uncaught InvalidState Error: Failed to execute 'openDatabase' on Window: enable to open database, failed to start transaction (14)"
[INFO:CONNSOLE(643)] "Uncaught TypeError: Cannot read property 'transaction' of excluded"

The above error message occurs and the app is unavailable.
Please give me some advice on how I can solve it.

**Comment by wilsolutions** [comment]
yeah, I did run into the same issue...
`TypeError: undefined is not an object (evaluating 'window.sqlitePlugin.openDatabase')`

Even using the code from the doc...

var db = window.sqlitePlugin.openDatabase({ name: 'my.db', location: 'default' }, function (db) {

    // Here, you might create or open the table.

}, function (error) {
    console.log('Open database ERROR: ' + JSON.stringify(error));
});

**Comment by breautek** [comment]
Sorry for the lack of response but closing the issue because of inactivity and lack of information that is required.

If you're using SQLite plugin, the SQL lite plugin is not maintained by Apache, so if you have a problem with that plugin, then you should open an issue on their repository.

If you're using the [WebSQL](https://cordova.apache.org/docs/en/9.x/cordova/storage/storage.html#websql) and you think you've found a bug, please do open a new issue and fill out all the requested information. Thanks.
