### ISSUE TITLE
MOBILE TOP 10: M5-INSUFFICIENT CRYPTOGRAPHYMOBILE

### ISSUE THREAD

**Issue by pkachhaw** [apache/cordova-android#638]
We have created a mobile app from ionic Cordova framwork and did a scan from WhiteHat Scan. It gives us following issue:

> Applications which use the Java Cryptography Architecture (JCA) for key generation, signing, or random number generation may not receive cryptographically strong values on Android devices due to improper initialization of the PRNG (pseudo-random number generator). Applications that directly invoke the system-provided OpenSSL PRNG without explicit initialization on Android are also affected. 
> 
> The application was found to be vulnerable because of issues related to the SecureRandom implementation. A static value is used each time the SecureRandom variable is created, which means that the results are not randomized on each individual instance. The code locations provided in the table below were identified as being the cause for the current risk status. It is encouraged to review these locations to determine if the violation occurred in an internal or external library. If the issue was found in an external library, it is not possible to determine if the affected portion of code is being triggered from the application's Java source code. In this case, it may not be possible to locate and resolve this issue.

**And Details for the issue are as:**

> Signature: ()I
> Class:  Lorg/apache/cordova/CordovaBridge;
> Method: generateBridgeSecret
> 
>  
> RECOMMENDATION
> To avoid being vulnerable to Secure Random, ensure that you properly initialize the underlying pseudo-random number generator.
> 
> Developers who use JCA for key generation, signing or random number generation should explicitly initialize the PRNG with entropy from /dev/urandom or /dev/random. Also, developers should evaluate whether to regenerate cryptographic keys or other random values previously generated using JCA APIs such as SecureRandom, KeyGenerator, KeyPairGenerator, KeyAgreement, and Signature.
> A suggested implementation is provided [here](https://android-developers.googleblog.com/2013/08/some-securerandom-thoughts.html)

**Comment by brodybits** [comment]
Thanks for reporting. In general security reports should be sent *privately* to <private@cordova.apache.org> or <security@apache.org>.

Here is my response:

The linked article seems to be over 5 years old.

I would not expect this to be an issue with newer Android OS versions: <https://github.com/apache/cordova-android/blob/7b17abc5553ca14f69081a2175f787d4a0550f0f/framework/src/org/apache/cordova/CordovaBridge.java#L114-L116>

Note that support for Android 4.3 was already dropped: <https://cordova.apache.org/docs/en/latest/guide/platforms/android/#requirements-and-support>

I do think it would be better if we would use a 20-byte byte array instead of a random integer as described in the following articles:
- https://developer.android.com/reference/java/security/SecureRandom
- https://tersesystems.com/blog/2015/12/17/the-right-way-to-use-securerandom/

Some more resources:
- https://stackoverflow.com/questions/25817133/does-the-android-implementation-of-securerandom-produce-true-random-numbers
- https://android-developers.googleblog.com/2016/06/security-crypto-provider-deprecated-in.html
- https://android-developers.googleblog.com/2013/08/some-securerandom-thoughts.html (the article linked in the description)
- other results of https://www.google.com/search?q=android+secure+random

**Comment by breautek** [comment]
> Android has developed patches that ensure that Android’s OpenSSL PRNG is initialized correctly. Those patches have been provided to OHA partners and have been checked into the Android tree. Applications which run exclusively on Android KitKat (4.4) or above do not need to take any special action to work around this bug.

As this only affects android devices < android 4.4, which we haven't supported in quite some time, this doesn't appear to be valid. I'll however make a PR to remove the lint suppression for `TruelyRandom`, which is not needed anymore, and I think would be best to not suppress lints unless we have a good reason for it.
