### ISSUE TITLE
CordovaActivity goes in pause

### ISSUE THREAD

**Issue by PDACN** [apache/cordova-android#646]
when I start NewActivity (using this.cordova.startActivityForResult) from CordovaPlugin,
after X minutes, usually 10/15 mins, CordovaActivity goes in pause,
if I send CordovaCallback from CordovaPlugin (using this.cordova.getThreadPool().execute(() -> cordovaCB.sendPluginResult(pluginResult))) nothing happens untill I close my NewActivity and return on CordovaActivity.

my cordova version read in CordovaWebView is this: CORDOVA_VERSION = "7.0.0";

**Comment by breautek** [comment]
I'm not sure what the expected behaviour but I believe this is the intended behaviour. An activity is a single, focused thing that the user can do, so naturally if you start a new activity, the old activity will go into a paused state.

If you think you've found a bug, feel free to open a new issue with all the requested information filled out.
