### ISSUE TITLE
Is there a way to change the version of Gradle Plugin?

### ISSUE THREAD

**Issue by nrikiji** [apache/cordova-android#650]
Would you please tell me if there is a way to change without fiddling the code directly...

```
buildscript {

    ・・・

    dependencies {
        // I want to rewrite this value
        classpath 'com.android.tools.build:gradle:3.2.0'
    }
}
```

https://github.com/apache/cordova-android/blob/master/framework/build.gradle#L34

**Comment by breautek** [comment]
You can extend the gradle config (see the [docs](https://cordova.apache.org/docs/en/latest/guide/platforms/android/index.html#extending-buildgradle)) but I don't think you can override/rewrite defined dependencies in gradle.

Also changing the gradle plugin version is not recommended. More often than not, the gradle plugin updates includes breaking changes.

**Comment by thibaultv** [comment]
Hi @nrikiji, I encounter the same problem recently. I need to use _<queries>_ element in the AndroidManifest.xml.
However, it's only compatible since some patch of [Android Gradle Plugin](https://stackoverflow.com/a/62969918).
2 possibilities:
- Upgrade to last version of Cordova Android (10.x)
- Cordova Android 8 (v3.3.0) / 9 (v4.0.0) : Use a hook that modify the version. I haven't tested but this [hook](https://stackoverflow.com/a/70187922) seems to make the job.
