### ISSUE TITLE
WebApp with cordova have communication problem on Citrix MDX wrapper

### ISSUE THREAD

**Issue by skabibmc** [apache/cordova-android#728]
# Bug Report
WebApp with cordova have communication problem on Citrix MDX wrapper
## Problem
We have mobile application that use cordova and it's wrap by Citrix MDX wrapper - all calls to server are failed.
when troubleshooting the issue with Citrix, they found that the app is using “SystemWebChromeClient” hooking for its network calls, which isn’t supported by the Citrix MDX wrapper.

 When I asked Citrix what they do support, they recommended that “SystemWebViewClient” is used instead.

As per my understanding - cordova using both clients. is it possible to configure cordova to use only one ?

## Checklist

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

**Comment by breautek** [comment]
I'm not sure if that makes a whole lot of sense... as Cordova uses `SystemWebView` which extends  `android.webkit.WebView` and that class makes use of both a `WebViewClient` (Which is what `SystemWebViewClient` extends) AND a `WebChromeClient` (which is what `SystemWebChromeClient` extends)

So yes... Cordova uses both clients, but that's because that is how you use the Android SDK.

I should mention that I'm not an Android developer and my knowledge is limited, but I'm just going off what I see at the Android [reference](https://developer.android.com/reference/android/webkit/WebView)

You haven't provided any details on how the requests is failing exactly but you haven't mentioned any Content Security Policy so if you are having network issues, I would double check that first. You can find the documentation [here](https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-whitelist/#content-security-policy)

**Comment by skabibmc** [comment]
Hi @breautek , Thanks for your answer.
We don't have any network issue , The problem is occur only when our customer is trying to wrap the application in citrix MDX wrapper.
Once it's wrap with citrix all attempts to communicate with our server are fail.
Per citirx team this is occur since we are using SystemWebChromeClient and not SystemWebViewClient , which for me - make no sense , cause as you said cordova using both.
So I wounder if there is a way to configure cordova to use only SystemWebViewClient.

**Comment by janpio** [comment]
> We don't have any network issue

>  Once it's wrap with citrix all attempts to communicate with our server are fail.

That sounds like a network issue to me ;)

**Comment by breautek** [comment]
> So I wounder if there is a way to configure cordova to use only SystemWebViewClient.

I did some more reading up on the difference between the android classes `WebViewClient` and `WebChromeClient`. Short answer is no, I think for Cordova both is required.

`WebViewClient` is used for overriding some functions related to the web browser page loading.
`WebChromeClient` is used for overriding some javascript APIs like `alert`.

Cordova uses `SystemWebChromeClient` to override some functions such as `prompt`, which is used for the cordova bridge so that javascript can send commands to call native functions.

If you want further assistance, I think you're going to have to post all relevant information about the network error.

**Comment by breautek** [comment]
On another thought... maybe Citrix is referring to the WebView implementation. By default android uses Chrome. But you can change it to the Android System Webview by going to Settings -> Developer options -> WebView Implementation

I don't know if this will break Cordova.

**Comment by breautek** [comment]
> when troubleshooting the issue with Citrix, they found that the app is using “SystemWebChromeClient” hooking for its network calls, which isn’t supported by the Citrix MDX wrapper.

This also doesn't really make a whole lot of sense. You can view the SystemWebChromeClient code [here](https://github.com/apache/cordova-android/blob/master/framework/src/org/apache/cordova/engine/SystemWebChromeClient.java). There's no methods being overridden related to network requests.

**Comment by janpio** [comment]
The simplest way to move this forward:

Is this reproducible in a new, plain Cordova app? A minimal reproduction repository would really help to debug and later fix this issue. More information on how to create one: https://github.com/apache/cordova-contribute/blob/master/create-reproduction.md

Then we can just look at what is happening.

**Comment by breautek** [comment]
Closing due to lack of response from OP.
