### ISSUE TITLE
Failed to compile 8.0.0 with high version code

### ISSUE THREAD

**Issue by videmort** [apache/cordova-android#730]
# Bug Report

## Problem
Doesn't compile if android-versionCode is too high

### Command or Code
Just run cordova build android with this config.xml version code config -->  android-versionCode="1613011076"

### Version information
Cordova 9 and cordova-android 8.0.0

### Console Error
versionCode is set to -1049758422 in product flavor armv7, but it should be a positive integer.

## Checklist

- [ X] I searched for existing GitHub issues
- [ X] I updated all Cordova tooling to most recent version
- [X ] I included all the necessary information above

**Comment by janpio** [comment]
What does "doesn't compile" mean?
Do you get an error message?
Or does it compile, but have a strange `versionCode` set?

**Comment by videmort** [comment]
hi @janpio  as i commented --> The error

versionCode is set to -1049758422 in product flavor armv7, but it should be a positive integer.

How to reproduce 
Set versionCode="1613011076" on config.xml and run cordova build android

**Comment by breautek** [comment]
What I think is happening is the versionCode is multiplied by 10. See [line 253](https://github.com/apache/cordova-android/blob/4cf3dcfaae6dc82ddb1ccf439d209cbcc2f474a0/bin/templates/project/app/build.gradle#L253)

This becomes a problem because the max versionCode integer that [Google](https://developer.android.com/studio/publish/versioning) allows is `2100000000`.

While 1613011076 is not greater than 2100000000.... 16130110760 (1613011076 * 10) is.

**Comment by breautek** [comment]
I should also add that changing this could be dangerous... as you can't publish APKs to the google store if the versionCode is lower than one that already exists on the play store.

**Comment by janpio** [comment]
I can't reproduce the issue. An app with `versionCode="1613011076"` in `config.xml` builds and runs just fine for me.

**Comment by janpio** [comment]
Ahh, it's `android-versionCode="1613011076"`. 

But this also builds fine and creates this in `AndroidManifest.xml`:
`<manifest android:hardwareAccelerated="true" android:versionCode="1613011076" android:versionName="1.0.0" package="io.cordova.hellocordova" xmlns:android="http://schemas.android.com/apk/res/android">`

**Comment by dpogue** [comment]
> What I think is happening is the versionCode is multiplied by 10. See [line 253](https://github.com/apache/cordova-android/blob/4cf3dcfaae6dc82ddb1ccf439d209cbcc2f474a0/bin/templates/project/app/build.gradle#L253)

Note that this is not the default behaviour, and something that must explicitly be opted in to by passing flags to gradle or editing the settings.gradle file in the project. It's possible that a plugin could be overriding that setting.

**Comment by breautek** [comment]
While Google says the max `versionCode` allowed is 2100000000. I can confirm that you can use a version code higher than that and it will still build successfully.

It will however start to fail once you exceed a value of 2147483647 (signed 32-bit integer range) producing the error that @videmort described.

@dpogue is right though, the versionCode is only multiplied by 10 if either multiple APKs is enabled, or force ABI digit is enabled. I missed that in my first post.

**Comment by videmort** [comment]
@janpio  It happen with ALL cordova apps using cordova-android 8.0.0 and cordova 9 cli

**Comment by janpio** [comment]
Not for me:

https://github.com/janpio/cordovaAndroid730

```
E:\Projects\throwaway\cordovaAndroid730 (master -> origin) (helloworld@1.0.0)
λ cat config.xml | grep widget
<widget android-versionCode="1613011076" id="io.cordova.hellocordova" version="1.0.0" xmlns="http://www.w3.org/ns/widgets" xmlns:cdv="http://cordova.apache.org/ns/1.0">
</widget>

E:\Projects\throwaway\cordovaAndroid730 (master -> origin) (helloworld@1.0.0)
λ cordova -v
9.0.0 (cordova-lib@9.0.1)

E:\Projects\throwaway\cordovaAndroid730 (master -> origin) (helloworld@1.0.0)
λ cordova platform list
Installed platforms:
  android 8.0.0
Available platforms:
  browser ^6.0.0
  electron ^1.0.0
  ios ^5.0.0
  osx ^5.0.0
  windows ^7.0.0

E:\Projects\throwaway\cordovaAndroid730 (master -> origin) (helloworld@1.0.0)
λ cordova build android
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\Jan\AppData\Local\Android\sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :app:preBuild UP-TO-DATE
> Task :CordovaLib:preBuild UP-TO-DATE
> Task :CordovaLib:preDebugBuild UP-TO-DATE
> Task :CordovaLib:checkDebugManifest UP-TO-DATE
> Task :CordovaLib:processDebugManifest UP-TO-DATE
> Task :app:preDebugBuild UP-TO-DATE
> Task :CordovaLib:compileDebugAidl NO-SOURCE
> Task :app:compileDebugAidl NO-SOURCE
> Task :CordovaLib:packageDebugRenderscript NO-SOURCE
> Task :app:compileDebugRenderscript UP-TO-DATE
> Task :app:checkDebugManifest UP-TO-DATE
> Task :app:generateDebugBuildConfig UP-TO-DATE
> Task :app:prepareLintJar UP-TO-DATE
> Task :app:generateDebugSources UP-TO-DATE
> Task :CordovaLib:compileDebugRenderscript UP-TO-DATE
> Task :CordovaLib:generateDebugBuildConfig UP-TO-DATE
> Task :CordovaLib:generateDebugResValues UP-TO-DATE
> Task :CordovaLib:generateDebugResources UP-TO-DATE
> Task :CordovaLib:packageDebugResources UP-TO-DATE
> Task :CordovaLib:generateDebugRFile UP-TO-DATE
> Task :CordovaLib:prepareLintJar UP-TO-DATE
> Task :CordovaLib:generateDebugSources UP-TO-DATE
> Task :CordovaLib:javaPreCompileDebug UP-TO-DATE
> Task :CordovaLib:compileDebugJavaWithJavac UP-TO-DATE
> Task :CordovaLib:processDebugJavaRes NO-SOURCE
> Task :CordovaLib:transformClassesAndResourcesWithPrepareIntermediateJarsForDebug UP-TO-DATE
> Task :app:javaPreCompileDebug UP-TO-DATE
> Task :app:mainApkListPersistenceDebug UP-TO-DATE
> Task :app:generateDebugResValues UP-TO-DATE
> Task :app:generateDebugResources UP-TO-DATE
> Task :app:mergeDebugResources UP-TO-DATE
> Task :app:createDebugCompatibleScreenManifests UP-TO-DATE
> Task :app:processDebugManifest UP-TO-DATE
> Task :app:processDebugResources UP-TO-DATE
> Task :app:compileDebugJavaWithJavac UP-TO-DATE
> Task :app:compileDebugNdk NO-SOURCE
> Task :app:compileDebugSources UP-TO-DATE
> Task :app:mergeDebugShaders UP-TO-DATE
> Task :app:compileDebugShaders UP-TO-DATE
> Task :app:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:mergeDebugShaders UP-TO-DATE
> Task :CordovaLib:compileDebugShaders UP-TO-DATE
> Task :CordovaLib:generateDebugAssets UP-TO-DATE
> Task :CordovaLib:packageDebugAssets UP-TO-DATE
> Task :app:mergeDebugAssets UP-TO-DATE
> Task :app:validateSigningDebug UP-TO-DATE
> Task :app:signingConfigWriterDebug UP-TO-DATE
> Task :app:transformClassesWithDexBuilderForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithExternalLibsDexMergerForDebug UP-TO-DATE
> Task :app:transformDexArchiveWithDexMergerForDebug UP-TO-DATE
> Task :app:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:compileDebugNdk NO-SOURCE
> Task :CordovaLib:mergeDebugJniLibFolders UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :CordovaLib:transformNativeLibsWithIntermediateJniLibsForDebug UP-TO-DATE
> Task :app:transformNativeLibsWithMergeJniLibsForDebug UP-TO-DATE
> Task :app:processDebugJavaRes NO-SOURCE
> Task :app:transformResourcesWithMergeJavaResForDebug UP-TO-DATE
> Task :app:packageDebug UP-TO-DATE
> Task :app:assembleDebug UP-TO-DATE
> Task :app:cdvBuildDebug UP-TO-DATE

BUILD SUCCESSFUL in 1m 24s
42 actionable tasks: 42 up-to-date
Built the following apk(s):
        E:\Projects\throwaway\cordovaAndroid730\platforms\android\app\build\outputs\apk\debug\app-debug.apk
```

Let me know if you spot my error - or even better just provide a reproduction repo yourself.

**Comment by videmort** [comment]
@janpio I create one pull request --> https://github.com/janpio/cordovaAndroid730/pulls.

Using crosswalk plugin it fails
 *What went wrong:
A problem occurred configuring project ':app'.
> versionCode is set to -1049758432 in product flavor armv7, but it should be a positive integer.
  See https://developer.android.com/studio/publish/versioning#appversioning for more information.


I use that plugin because is the only way to get an x64 build. 
From 1 August is mandatory from google --> https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html

**Comment by janpio** [comment]
Ok, then this is a problem with that plugin and not cordova-android.

If you refer to https://github.com/crosswalk-project/cordova-plugin-crosswalk-webview, this has a big "UNMAINTAINED" written on the top.

And if your actual problem is that you think some Google requirement is not fulfilled by Cordova Android, open an issue how to solve this and not some incompatibility with some plugin.

**Comment by videmort** [comment]
@janpio  works perfect with cordova-android 7.1.4 so... is not from the CW plugin...

**Comment by breautek** [comment]
@videmort  I use crosswalk in my projects and I had to do several changes to both Crosswalk and cordova-android make building split 32bit/64bit APKs to work properly because they clashed in the build configuration. I'm using cordova-android 8 + crosswalk and I'm building 32bit/64bit apks, but I still think your problem is that you're versionCode is simply too high. Even crosswalk does the same thing as described in my earlier [post](https://github.com/apache/cordova-android/issues/730#issuecomment-490997629).

> If you do not have any .so files in your APK, you are already 64-bit compliant.

It is worth mentioning that Cordova fits under this umbrella. There is a discussion that can be found [here](https://github.com/apache/cordova-android/issues/647). Cordova itself has no native libraries. 

If you do use crosswalk, then you will need a 64bit binary because crosswalk includes native .so libraries. So removing crosswalk may drop the requirement of needing a 64bit apk altogether... depending on if your project uses another third-party plugin that includes a native library file of course.

**Comment by janpio** [comment]
So it is actually the crosswalk plugin triggering this: https://github.com/apache/cordova-android/issues/730#issuecomment-491037151

**Comment by breautek** [comment]
> So it is actually the crosswalk plugin triggering this: [#730 (comment)](https://github.com/apache/cordova-android/issues/730#issuecomment-491037151)

It's been awhile since I made my own modifications so my memory now is a bit hazy. Xwalk had their own build script that handled building multiple APKs behind their own flag, and cordova had theirs and I know they clashed. I believe Cordova overwrote xwalks config, so xwalk may have done something to enable cordova to write multiple apks and triggered [#730 (comment)](https://github.com/apache/cordova-android/issues/730#issuecomment-491037151) but I'm not 100% sure.

But they both multiplied the versionCode by 10 and that's because you need another digit to represent the APK type. So regardless of using plain cordova or crosswalk using a versionCode that high will be problematic. So after learning that the issue comes from trying to use multiple APKs, I'm confident this issue really stems from using an extreme high versionCode.

Google recommends the version code should be a template that somewhat mimic the version e.g. `3.1.14` should be something like `30114`, which is what Cordova does by default. I'm not sure if `1613011076` follows such recommendation.

**Comment by videmort** [comment]
@breautek  @dpogue  @janpio  thanks for help
