### ISSUE TITLE
How to run shell/Command Line Program/Unix Executable in cordova app？

### ISSUE THREAD

**Issue by hugetiny** [apache/cordova-android#756]
How to run shell/Command Line Program/Unix Executable in cordova app？
such as node
![image](https://user-images.githubusercontent.com/19659202/56096552-4271fb80-5f1c-11e9-9fbb-13f6b67fd6b0.png)

**Comment by janpio** [comment]
You generally don't. Cordova offers a webview where you can run you web/html app.

**Comment by hugetiny** [comment]
yes，but I still need a background Unix Executable

**Comment by breautek** [comment]
I can't speak for iOS very much but you cannot simply run native binaries on android. Android has something called NDK (Native Development Kit) to build native executables for android, callable from java code.

To make it accessible via cordova, you'll then also need to create a Cordova plugin.

Note that you can't simply include unix executables because most phones run on the arm or arm64 architecture, and most pcs run on x86/x64 architecture. You'll need to compile a binary for every architecture you want to support.

One final note... this might be old, but Apple did at one point of time had policies that forbid you from including your own implementation of webviews or javascript engines. On iOS you must use their javascript engine provided by the operating system. This means you cannot run Node on iOS.

Hope this helps you get started.

**Comment by breautek** [comment]
Closing due to lack of response from the OP. If you require further assistance, I invite you to join our [slack](http://slack.cordova.io/) for support style questions like this one.
