### ISSUE TITLE
Cordova Resume and Pause Events are fired when Hardware plugin is used (eg. Camera)

### ISSUE THREAD

**Issue by joaolnpr** [apache/cordova-android#760]
### Issue Type
 
- [X] Bug Report
- [ ] Feature Request
- [ ] Support Question

## Description

Cordova platform resume and pause is fired whenever a plugin which is using hardware if called. 
e.g. workflow

Cordova platform Ready
App Access Camera
Cordova platform Pause
Take Picture, Close Camera
Cordova platform Resume

## Information

Ideal scenario is not firing the resume and pause events when we are using device hardware. 
 
 
### Environment, Platform, Device
 Android and IOS

### Version information
 Cordova 8

## Checklist
 

- [X] I searched for already existing GitHub issues about this
- [ ] I updated all Cordova tooling to their most recent version
- [X] I included all the necessary information above

**Comment by breautek** [comment]
Can you describe how this is problematic in your case?

When you use the camera, the app does go in the background to bring the camera activity up, so naturally pause/resume events should fire when using the camera, or anything that puts the main app activity to the background. I think this is important because it allows the developer to stop doing any kind of app logic that might be resource demanding, which is particularly important for users running budget phones with limited resources as the camera is a resource demanding activity itself.

**Comment by jcesarmobile** [comment]
Cordova events fire when native events fire, and they fire when an Intent is launched, such us camera plugin does. 
If you want to ignore them, use some boolean that you set before calling the camera and unset on the success/failure callbacks and use it on the event listeners.
We are not going to change it.
