### ISSUE TITLE
Load UI/Webview without Activity context.

### ISSUE THREAD

**Issue by NitzDKoder** [apache/cordova-android#762]
**Hi Folks,**

Currently the loading UI/Webview is bound to activity.

My app is does the fetch(JS level) data from remote/local server on bootup/ App Swipe from recents.

With androidQ activity cant be brought to foreground automatically.
 
https://developer.android.com/preview/privacy/background-activity-starts

https://stackoverflow.com/questions/18865035/android-using-webview-outside-an-activity-context

**Feature:**

Load UI/Webview with out Activity context. This should be configurable in cordova.

https://stackoverflow.com/questions/32150196/loading-a-url-from-webview-without-showing-it

Thanks

**Comment by dpogue** [comment]
This feels to me like it’s outside the scope of what Cordova is intended to handle. If we made this configurable and supported, then people would start expecting plugins to also support it, and the maintenance cost of it becomes a major overhead. We should be seeking to reduce the complexity of maintenance rather than increase it.

If this is something you need and want to support at the native project level, modifying your Cordova-Android project is one option or perhaps looking into options like [Capacitor](https://capacitor.ionicframework.com/) that make the native project more accessible to editing.
