### ISSUE TITLE
Nightly is outdated

### ISSUE THREAD

**Issue by steebchen** [apache/cordova-android#810]
# Bug Report

Installing `cordova-android@nightly` from npm installs `8.1.0-nightly.2019.6.28.4cf3dcfa`, which seems to be commit 4cf3dcfaae6dc82ddb1ccf439d209cbcc2f474a0 from April 13. However, this is outdated as there are many new commits which should be included in the nightly.

It would be great if this could be fixed so one can install the nightly build from npm without having to switch to git (which can result in buggy behaviour with cordova sometimes).

**Comment by dpogue** [comment]
It appears that the cause of this is due to npm no being longer installed on the Apache Jenkins buildmachines. :disappointed: I'm also not sure why we haven't been getting build failure emails to the mailing list.

I'll try to report this to INFRA later today, but it might also be worth investigating whether GitHub Actions could replace Jenkins for the nightly builds. (My current thinking is that the nightly build might be too complex because of the number of repos it clones and unconventional check-out patterns)

**Comment by steebchen** [comment]
My opinion: GitHub CI/CD is definitely a good solution for the long term, but taking into account it's in beta right now and judging how the "old" GH actions went I would wait for GA and re-activate jenkins for now (if that's not too much trouble)

**Comment by dpogue** [comment]
I _think_ I've got this sorted out on the Apache Jenkins for now. There should be a new nightly build from today, and hopefully it will work from now on.

**Comment by steebchen** [comment]
Thanks!
