### ISSUE TITLE
Could not get unknown property 'cdvCompileSdkVersion'

### ISSUE THREAD

**Issue by ctfrancia** [apache/cordova-android#821]
# Bug Report

## Problem
ever since adding google play services I have been following the rabbit holes of _this issue_ and _that issue_ and at this point I have no idea where the error lies. I have been getting the error:

> * What went wrong:
A problem occurred evaluating project ':com.google.playservices:google-play-services_lib'.
> Could not get unknown property 'cdvCompileSdkVersion' for object of type com.android.build.gradle.LibraryExtension.

after reading files I went and found that downgrading to 6.4.0 solved it. did that got another error, then read the post #485, so I upgraded back to 8.0.0 and still getting the issue.  

### What is expected to happen?
to compile and run

### What does actually happen?
the error above

#### config.xml
```
<preference name="android-minSdkVersion" value="19" />
// ...
    <platform name="android">
        <resource-file src="google-services.json" target="google-services.json" />
```

### Command or Code

`$ ionic cordova run android --device`

### Environment, Platform, Device

mac osx

### Version information

```
Ionic:

   Ionic CLI                     : 5.2.7 (/usr/local/lib/node_modules/ionic)
   Ionic Framework               : @ionic/angular 4.8.1
   @angular-devkit/build-angular : 0.801.3
   @angular-devkit/schematics    : 8.3.1
   @angular/cli                  : 8.1.3
   @ionic/angular-toolkit        : 2.0.0

Cordova:

   Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
   Cordova Platforms : android 8.0.0, ios 4.5.5
   Cordova Plugins   : cordova-plugin-ionic-keyboard 2.1.3, cordova-plugin-ionic-webview 4.1.1, (and 14 other plugins)

Utility:

   cordova-res : 0.6.0 
   native-run  : 0.2.7 (update available: 0.2.8)

System:

   NodeJS : v12.7.0 (/usr/local/lib/node_modules/node/bin/node)
   npm    : 6.10.2
   OS     : macOS Mojave
   Xcode  : Xcode 10.2.1 Build version 10E1001
```

## Checklist

- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by ctfrancia** [comment]
I had a bad plugin installed that was 5 years untouched. I need a drink.

**Comment by Shery11** [comment]
Hi, getting same error on building an old application. Can you tell which plugin did you remove ?

**Comment by Dicus-es** [comment]
I think for me if I remember correctly, was that it needs to be building android at 8.1.0

**Comment by ctfrancia** [comment]
I don't remember exactly now, but I think that it was the firebase one which is unmaintained

**Comment by jongbonga** [comment]
I'm getting the same issue with ionic 5 & capacitor.
Any solution yet?

**Comment by jongbonga** [comment]
1 year later :(

**Comment by JorisDebonnet** [comment]
> 
> 
> I'm getting the same issue with intercom plugin...
> Any solution yet?

I found a workaround, but it's dirty 😕

1. Intercom's Cordova plugin, even the very most recent one, wants `cdvCompileSdkVersion` and `cdvBuildToolsVersion` values, so okay fine, let's created them. They go as extra lines into `variables.gradle`. The first is simply a copy of the existing `compileSdkVersion` there, and for the `cdvBuildToolsVersion` value, I looked up the latest installed version via Tools > SDK Manager > Build tools.
2. The next thing it complains about is that `applicationId` is being set by a plugin/library, which is forbidden. This is where it gets dirty, because I could only fix this by editing a file in `node_modules`. Specifically, I commented out lines 7 and 8 in `node_modules/cordova-plugin-intercom/src/android/build-extras-intercom.gradle`. Then, Android Studio was happy to build my project, and Intercom works. (This might have bad side-effects if a user has another app with the Intercom plugin. I did not test this.) I added this to my documentation because I'll need to edit that file after each npm command...

I'm sure this is very bad practice etc, probably caused by not understanding what is actually wrong. I hope to solve it better in the future, but it seems to work for now.

**Comment by Franco-Alejandro** [comment]
Did anyone find a different fix for this? I'm facing the same issue with the latest intercom package, basically 

> Could not get unknown property 'cdvBuildToolsVersion' for project ':app' of type org.gradle.api.Project.

For some reason i cannot set this variable from the config.xml

**Comment by danieldanielecki** [comment]
Some outdated packages cause it, such as `cordova-plugin-browsertab`, see: https://github.com/apache/cordova-android/issues/821.

There are multiple ways to solve this, it's even [an example from Cordova docs][1].

That one working for me - add `cdvMinSdkVersion=21` inside `gradle.properties`. Haven't tried the other ones, but as per [cordova-plugin-browsertab#43 (comment)][2], it should work at least with exporting as environmental variable.


  [1]: https://cordova.apache.org/docs/en/11.x/guide/platforms/android/index.html#setting-gradle-properties
  [2]: https://github.com/google/cordova-plugin-browsertab/issues/43#issuecomment-1145054303
