### ISSUE TITLE
cordova build android error

### ISSUE THREAD

**Issue by longting** [apache/cordova-android#829]
# Bug Report
cordova android@^7.1.4   
corodva 8.1.2  

## Problem
execute `npm install`
execute `cordova build android`  failure 

### What is expected to happen?
build is OK. 

### What does actually happen?
yesterday is OK.  No plugins added。

## Information
execute `npm install`
![1](https://user-images.githubusercontent.com/5129611/65328121-24ee3f80-dbe8-11e9-84f9-415e49d66801.png)

![image](https://user-images.githubusercontent.com/5129611/65328168-44856800-dbe8-11e9-8ab6-995a5576ba60.png)

---------------------
execute `cordova build android`  failure 
this is androidx and  android.support conflict. 
```
:app:processDebugManifestD:\work\myproject\kaixinyunshi\kaiyun-app\platforms\android\app\src\main\AndroidManifest.xml:22:18-91 Error:
        Attribute application@appComponentFactory value=(android.support.v4.app.CoreComponentFactory) from [com.android.support:support-compat:28.0.0] AndroidManifest.xml:22:18-91
        is also present at [androidx.core:core:1.0.0] AndroidManifest.xml:22:18-86 value=(androidx.core.app.CoreComponentFactory).
        Suggestion: add 'tools:replace="android:appComponentFactory"' to <application> element at AndroidManifest.xml:5:5-91:19 to override.
```

### Command or Code
`cordova build android` 

### Environment, Platform, Device
Win7

### Version information
cordova android@^7.1.4   
corodva 8.1.2  
Win7

## Other
execute

**Comment by jcesarmobile** [comment]
You can't mix android x dependencies with regular dependencies, so this is probably caused by a plugin that didn't have a fixed version of the dependencies and now is picking latest one that uses Android X.
You'll have to check your plugins and see which one is bringing that dependency, or use a plugin that changes all dependencies to android x dependencies, such as https://github.com/apache/cordova-android/issues/565#issuecomment-486346219

Also you are using old versions of CLI and cordova-android, to report issues you have to be using latest versions to make sure the issue is still present.
