### ISSUE TITLE
How to enable WebView for a Cordova Hybrid Mobile App?

### ISSUE THREAD

**Issue by Devapal** [apache/cordova-android#856]
When I get context handles from code, I only see "Native". How do I enable WebView for a Cordova Mobile App (Hybrid). Is there a setting in project files that enables the WebView ? Please advise.

Unable to find a setting that sets the WebView = true

I am trying to get context handles for this Hybrid Mobile App ( Cordova ) and I see only native. I need to be able to get WebView to interact with the mobile elements for UI testing using Appium.

From the documentation, I can see that the method setWebContentsDebuggingEnabled is accountable for debugging web contents and is default set to false. How do I set this to true for a Cordova Mobile App (hybrid) project ? 

Further More: In my case, It is necessary to set to true the setWebContentsDebuggingEnabled property on the android.webkit.WebView element. How can I set this ?  

Source: appium.io/docs/en/writing-running-appium/web/hybrid

**Comment by breautek** [comment]
Not exactly sure on what you're asking but if you're trying to use the web inspector, the app needs to be built in debug mode, or you need to add [android:debuggable](https://developer.android.com/guide/topics/manifest/application-element) to your `<application>` tag in the `AndroidManifest.xml`

When this flag is set, the cordova library will allow the webview to be debuggable and accept the web inspector remote connection.

**Comment by Devapal** [comment]
@breautek Thats exactly what I want to do. thank you.

**Comment by Devapal** [comment]
For the Cordova 8 hybrid app, Can you specify the path of AndroidManifest.xml ?
I see several AndroidManifest.xml files

**Comment by breautek** [comment]
If you use the `cordova` command line to create your project it will be located under `<project-dir>/platforms/android/app/src/main/`

But you shouldn't need to modify the android manifest file to add debuggable yourself if you use the cordova command line. Cordova tooling does that already if you use the cordova build/run command without the `--release` flag.

Modifying the AndroidManifeset.xml is only required if you have a native app that you're embedding the cordova webview into. I was confused on what you meant exactly by "Hybrid mobile app" so I mentioned both ways just in case.

**Comment by Devapal** [comment]
Thank you for your prompt response! Appreciate it!

Quick question, After the above step of enabling WebView, Do I need to enable "Android System WebView" or "Chrome view" on my phone under developer options or Is that not necessary ?

**Comment by breautek** [comment]
I don't believe chrome webview is required, but my phone and all phones ive used i think has the chrome webview enabled, not the android system webview.

**Comment by jcesarmobile** [comment]
If you run the app in debug mode then it’s enabled
https://github.com/apache/cordova-android/blob/46a036ef265951d5371936b37d7296fa47fb28ce/framework/src/org/apache/cordova/engine/SystemWebViewEngine.java#L176

**Comment by ash123349** [comment]
@breautek in my mobile(Vivo Y21) and other mobiles webview is not working so what if i want to use chrome view instead of webview.
getting error : application does not have sufficient geolocation permissions.
what should i do?

**Comment by breautek** [comment]
> getting error : application does not have sufficient geolocation permissions.

If you're getting permission errors, i would check the permissions settings explicitly and enable them to see if the error goes away. Additionally there is a bug that affects android 12 devices in our current release where you **must** request high accuracy. Requesting coarse location (`enableHighAccuracy` false) will always result in a permission denied. This is fixed in our development `master` branch, but isn't released yet.

> what if i want to use chrome view instead of webview.

The short answer is unfortunately that isn't a decision you can make as a developer.

The long answer...

The AOSP does allow users to install different system webviews, and with developer mode enabled, they can choose different webview implementations. But these options are hidden behind developer tools, so not only it's up to the device user, the user must go through the steps of enabling developer mode on their device.

Once upon a time, Intel had the Crosswalk project which was a fork of Chromium to build chromium webview as a system library that can be embedded with android apps. This isn't a supported configuration by Google but the goal was to replace the old android browser as the webview with chromium as their system webview, which sounds like exactly what you're asking for... but Intel cut the project as it was too difficult to maintain, and by 2017, the AOSP was already using Chrome as their system webview.

So neither of these are reasonable solutions.
