### ISSUE TITLE
Impossible to create new app and build it for Android.

### ISSUE THREAD

**Issue by maxdeepfield** [apache/cordova-android#875]
# Bug Report

## Problem

When create new cordova project, add android platform and open android folder with Android Studio, it is unable to sync gradle settings and set up gradle wrapper to make build works.

### What is expected to happen?

Android Studio "does the gradle magic without errors"

### What does actually happen?

app/build gradle error
ERROR: Unable to load class 'com.android.builder.model.BuildType'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

## Information

Platform removed and added
All rebuilt and cleaned
Many gradle versions tested

### Environment, Platform, Device +  Version information
windows 10 1909
android studio 3.5.2
cordova 9.0.0
cordova-android 8.1.0
gradle 3/4/5/6 - whatever

## Checklist
- [ x] I searched for existing GitHub issues
- [ x] I updated all Cordova tooling to most recent version
- [ x] I included all the necessary information above
- [ x] I tried reboot/reinstall anything

**Comment by breautek** [comment]
You can try deleting the gradle cache. Most gradle wrapper installation issues are due to a bad cache. (Android Studio perhaps handle this smarter than Cordova?) I'm not sure where this is located on the windows filesystem however.

According to https://stackoverflow.com/a/53410633/4685664 the gradle cache is located at `%userprofile%.\gradle` by default.

You can then move/delete the contents of the `gradle/cache` directory. This will make gradle download each version you require (latest cordova currently requires `4.10.3`) from scratch again.

**Comment by maxdeepfield** [comment]
@breautek thanks for your help, completely clean and terminate .gradle home directory worked for me, but it was possible only using special utilites, seems caches were locked and not emptied on request. My problem gone.
