### ISSUE TITLE
Cordova Build Android shows error

### ISSUE THREAD

**Issue by buchion** [apache/cordova-android#899]
cordova run android
Discovered saved plugin "cordova-plugin-splashscreen". Adding it to the project
Failed to restore plugin "cordova-plugin-splashscreen" from config.xml. You might need to try adding it again. Error: Cannot find plugin.xml for plugin "cordova-plugin-splashscreen". Please try adding it again.
Checking Java JDK and Android SDK versions
ANDROID_SDK_ROOT=undefined (recommended setting)
ANDROID_HOME=C:\Users\buchi\AppData\Local\Android\sdk (DEPRECATED)
Subproject Path: CordovaLib
Subproject Path: app
chmod: File not found: C:\Users\buchi\Desktop\Coou\platforms\android\gradle\wrapper\gradle-wrapper.properties

sed: no such file or directory: C:\Users\buchi\Desktop\Coou\platforms\android\gradle\wrapper\gradle-wrapper.properties

'sh' is not recognized as an internal or external command,
operable program or batch file.
C:\Users\buchi\Desktop\Coou\platforms\android\gradlew: Command failed with exit code 1 Error output:
'sh' is not recognized as an internal or external command,
operable program or batch file.

**Comment by SukantPal** [comment]
Try opening it in android studio and running the project. It might show an error and suggest an easy fix (one click).

**Comment by breautek** [comment]
Sorry for the lack of response... but I'll be closing this because I don't think this is an issue with the cordova tooling, but rather with your environment.

Something about your environment thinks you're on a unix machine instead of windows, which means NodeJS's [process.platform](https://nodejs.org/api/process.html#process_process_platform) is likely lieing to us.

If you still have this issue, I'd recommend using our [slack](http://slack.cordova.io/), which is a more appropriate place for support.

**Comment by mikebridge** [comment]
I run WSL2 and Windows side-by-side and I had the same problem.  I *believe* some npm libraries were corrupted due to a bad path that installed something into Windows that should have stayed with Linux.  Reinstalling nodejs/npm from scratch on Windows along with all `node_modules` was the only way I could fix it.  For good measure I also uninstalled and reinstalled the android platform.

**Comment by AlokJoshi** [comment]
> cordova run android Discovered saved plugin "cordova-plugin-splashscreen". Adding it to the project Failed to restore plugin "cordova-plugin-splashscreen" from config.xml. You might need to try adding it again. Error: Cannot find plugin.xml for plugin "cordova-plugin-splashscreen". Please try adding it again. Checking Java JDK and Android SDK versions ANDROID_SDK_ROOT=undefined (recommended setting) ANDROID_HOME=C:\Users\buchi\AppData\Local\Android\sdk (DEPRECATED) Subproject Path: CordovaLib Subproject Path: app chmod: File not found: C:\Users\buchi\Desktop\Coou\platforms\android\gradle\wrapper\gradle-wrapper.properties
> 
> sed: no such file or directory: C:\Users\buchi\Desktop\Coou\platforms\android\gradle\wrapper\gradle-wrapper.properties
> 
> 'sh' is not recognized as an internal or external command, operable program or batch file. C:\Users\buchi\Desktop\Coou\platforms\android\gradlew: Command failed with exit code 1 Error output: 'sh' is not recognized as an internal or external command, operable program or batch file.

Hi. In case you are monitoring this thread, I had the same issue but then I decided to use the bash interface to run the batch commands and everything worked smoothly.
