### ISSUE TITLE
Update codebase to ES6 syntax

### ISSUE THREAD

**Issue by SukantPal** [apache/cordova-android#905]
# Feature Request

## Motivation Behind Feature

I see that the codebase is currently using ES5 syntax. For future development, using ES6 syntax (classes, let & const, etc.) would be much more clean.

## Feature Description

I would be willing to spend time to do this conversion.

## Alternatives or Workarounds

N/A

**Comment by breautek** [comment]
This is something we are slowly moving towards.

**Comment by breautek** [comment]
I have confirmed that code that is intended to be ran inside a browser and/or webview must not be converted, unless support for android 4.4 is dropped.

The reasoning is because [android 4.4 uses chrome 33](https://developer.chrome.com/multidevice/webview/overview) where many of these features are not supported.
