### ISSUE TITLE
[Feature Request]: Ability to inspect/read setting for a platform device

### ISSUE THREAD

**Issue by jringbox** [apache/cordova-android#966]
# Feature Request

## Motivation Behind Feature

Ability to inspect/read setting for a platform device.  This solves the issue where an application has to make decisions based on user settings.  For example, if the application can produce notifications that are sensitive, the developer needs to know what the notification settings are under privacy and security.  If the notification setting is set to hidden, then all content can be set in the notification.  If the settings are not set to hidden then limited content needs to show in the notification on the device.

## Feature Description

Ability to inspect/read what settings are set on a platform device that is set by the user.

## Alternatives or Workarounds

There was one (cordova-plugin-device-settings) but it was deprecated and the github source was not available.  If there is something out there, please let me know.

Thanks!

**Comment by breautek** [comment]
I installed `cordova-plugin-device-settings` and looked at the source code that appeared in the `node_modules` and that plugin didn't do much anyway, it only provided an API to determine if the phone had developer mode enabled and nothing else.

[cordova-diagnostic-plugin](https://github.com/dpa99c/cordova-diagnostic-plugin#notifications-module) may have what you need.

In general, I think this is probably better off to be a plugin rather than a core feature. It appears that these [docs](https://developer.android.com/reference/android/provider/Settings) would be a good starting place for an android implementation.

**Comment by jringbox** [comment]
Yeah, I was trying to avoid that path.  I've never looked at the native android api and was afraid it would be painful to write a plugin.  I was hoping I missed something and there was a plugin out there.  I find it hard to believe that no one wants to know if the notification settings are hidden or not on android but maybe that option is not on iOS so, in general, no one cares enough from a business standpoint.
