### ISSUE TITLE
unexpected token {

### ISSUE THREAD

**Issue by veereshkorwar** [apache/cordova-android#973]
Hi
I have created ionic v1 project and tried checking the platforms using "cordova platforms" in command prompt then im getting error saying "unexpected token {"

i have tried uninstalling cordova and installing again ... but still same issue! Any help on the will be greatly appreciated.

![image](https://user-images.githubusercontent.com/32124177/81790727-6a6ace80-9523-11ea-8a45-a3885079dfa4.png)

![image](https://user-images.githubusercontent.com/32124177/81790753-76569080-9523-11ea-8881-b488dbec8394.png)

ionic version : 1.7.14
cordova version : 5.4.1
Node : 5.3.0
npm : 3.3.12

**Comment by erisu** [comment]
It appears that you are using a really old version of Cordova and node/npm.

The Cordova version that you are using is not supported. We generally support and push updates only the latest major release of Cordova which is currently 9.x.

Also, the version of the node you are running has already reached its end-of-life. The node team currently maintains only 10.x and over. https://nodejs.org/en/about/releases/

I would recommend upgrading:
* Node to the latest LTS. (currently 12.16.3)
* Cordova to the latest release. (currently 9.0.0)

**Comment by veereshkorwar** [comment]
@erisu  thanks .... but the project we are working on requires to use that specific versions of node,ionic and cordova . 
upgrading to latest would lead us to where  most of our project modules failed to support.

**Comment by breautek** [comment]
If you're unable to update for whatever reasons, then this is as far as we can provide support and respectfully you're on your own.

Your options are:
- Refactor your app so that it runs on modern & supported versions of software.
- Fork the libraries you use and apply fixes/patches to the version branches that you use.

The first option would be the recommended. Using out-of-date software tends to have security concerns as they don't receive security patches.
