### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by JaLe29** [apache/cordova-android#979]
# Bug Report

## Problem
I created fresh new app using
```
sudo npm install -g cordova
cordova create hello com.example.hello HelloWorld
.
.
cordova platform add android
```

I put bundled react app (created by `create react app`) into cordova `www` folder.

Also I removed `Content-Security-Policy` tag from root html.

I linked js and css files in root html and I sterted an android emulator.

### What is expected to happen?
Android app loads all react chunks.

### What does actually happen?
Android app does not loads all react chunks. I am getting 
```
Failed to load resource: net::ERR_FILE_NOT_FOUND [file:///static/media/play.d00c2962.png]
Failed to load resource: net::ERR_FILE_NOT_FOUND [file:///static/media/bg.377ecc72.png]
```
for some files (ONLY FOR SOME).

### Environment, Platform, Device

Windows 10, 64b.
"cordova-android": "^8.1.0" 

## Checklist
- [x] I searched for existing GitHub issues
- [x] I updated all Cordova tooling to most recent version
- [x] I included all the necessary information above

**Comment by breautek** [comment]
`file:///static/media/play.d00c2962.png` is not a valid url. Your application root is something like `file:///android_asset/www/` (going off memory, might be wrong but it's something similar)

I suspect you're referencing these files using an absolute path, e.g. `/myfile.png`. This is a common mistake because normally you would consider this relative to your webserver. In cordova, however, by prefixing `/`, you are starting at the root of the filesystem, since the files are hosted on the filesystem.

You should use relative urls, which are relative to the html document. So if those files lived in a static folder that is a sibling of the loaded html folder, the path would look like:

`./static/myfile.png`

Note: while you could specify the full android path, it is better to use relative urls as shown above to remain cross platform. For example, the iOS platform has a completely different file path to the root of your app.

Let me know if this helps.

**Comment by JaLe29** [comment]
Hi @breautek ,

thank you!

It is working.

**Comment by caubenganha** [comment]
Thank @breautek

**Comment by wasinr** [comment]
Hi, Anyone give me some more detail how to fixed this?
